package org.apache.sanselan.formats.tiff.constants;

import android.support.v4.app.FragmentTransaction;
import com.facebook.internal.FacebookRequestErrorClassification;
import com.facebook.stetho.server.http.HttpStatus;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.ads.dynamite.ModuleDescriptor;
import com.google.logging.type.LogSeverity;
import com.myfitnesspal.shared.service.syncv1.packets.request.AssociateBarcodeWithFoodRequestPacket.ResultCodes;
import com.samsung.android.sdk.accessory.SASocket;
import org.apache.sanselan.formats.tiff.constants.TagInfo.Offset;
import org.apache.sanselan.formats.tiff.constants.TagInfo.Text;
import org.apache.sanselan.formats.tiff.fieldtypes.FieldType;

public interface ExifTagConstants extends TiffDirectoryConstants, TiffFieldTypeConstants {
    public static final TagInfo[] ALL_EXIF_TAGS;
    public static final TagInfo EXIF_TAG_ACTIVE_AREA;
    public static final TagInfo EXIF_TAG_AFCP_IPTC;
    public static final TagInfo EXIF_TAG_ALIAS_LAYER_METADATA;
    public static final TagInfo EXIF_TAG_ALPHA_BYTE_COUNT;
    public static final TagInfo EXIF_TAG_ALPHA_DATA_DISCARD;
    public static final TagInfo EXIF_TAG_ALPHA_OFFSET;
    public static final TagInfo EXIF_TAG_ANALOG_BALANCE;
    public static final TagInfo EXIF_TAG_ANNOTATIONS;
    public static final TagInfo EXIF_TAG_ANTI_ALIAS_STRENGTH;
    public static final TagInfo EXIF_TAG_APERTURE_VALUE;
    public static final TagInfo EXIF_TAG_APPLICATION_NOTES;
    public static final TagInfo EXIF_TAG_ARTIST;
    public static final TagInfo EXIF_TAG_AS_SHOT_ICCPROFILE;
    public static final TagInfo EXIF_TAG_AS_SHOT_NEUTRAL;
    public static final TagInfo EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX;
    public static final TagInfo EXIF_TAG_AS_SHOT_WHITE_XY;
    public static final TagInfo EXIF_TAG_BACKGROUND_COLOR_INDICATOR;
    public static final TagInfo EXIF_TAG_BACKGROUND_COLOR_VALUE;
    public static final TagInfo EXIF_TAG_BAD_FAX_LINES;
    public static final TagInfo EXIF_TAG_BASELINE_EXPOSURE;
    public static final TagInfo EXIF_TAG_BASELINE_NOISE;
    public static final TagInfo EXIF_TAG_BASELINE_SHARPNESS;
    public static final TagInfo EXIF_TAG_BATTERY_LEVEL;
    public static final TagInfo EXIF_TAG_BAYER_GREEN_SPLIT;
    public static final TagInfo EXIF_TAG_BEST_QUALITY_SCALE;
    public static final TagInfo EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH;
    public static final TagInfo EXIF_TAG_BITS_PER_RUN_LENGTH;
    public static final TagInfo EXIF_TAG_BITS_PER_SAMPLE;
    public static final TagInfo EXIF_TAG_BLACK_LEVEL;
    public static final TagInfo EXIF_TAG_BLACK_LEVEL_DELTA_H;
    public static final TagInfo EXIF_TAG_BLACK_LEVEL_DELTA_V;
    public static final TagInfo EXIF_TAG_BLACK_LEVEL_REPEAT_DIM;
    public static final TagInfo EXIF_TAG_BRIGHTNESS;
    public static final TagInfo EXIF_TAG_BRIGHTNESS_VALUE;
    public static final TagInfo EXIF_TAG_CALIBRATION_ILLUMINANT_1;
    public static final TagInfo EXIF_TAG_CALIBRATION_ILLUMINANT_2;
    public static final TagInfo EXIF_TAG_CAMERA_CALIBRATION_1;
    public static final TagInfo EXIF_TAG_CAMERA_CALIBRATION_2;
    public static final TagInfo EXIF_TAG_CAMERA_SERIAL_NUMBER;
    public static final TagInfo EXIF_TAG_CELL_LENGTH;
    public static final TagInfo EXIF_TAG_CELL_WIDTH;
    public static final TagInfo EXIF_TAG_CFALAYOUT;
    public static final TagInfo EXIF_TAG_CFAPATTERN;
    public static final TagInfo EXIF_TAG_CFAPATTERN_2;
    public static final TagInfo EXIF_TAG_CFAPLANE_COLOR;
    public static final TagInfo EXIF_TAG_CFAREPEAT_PATTERN_DIM;
    public static final TagInfo EXIF_TAG_CHROMA_BLUR_RADIUS;
    public static final TagInfo EXIF_TAG_CLEAN_FAX_DATA;
    public static final TagInfo EXIF_TAG_CLIP_PATH;
    public static final TagInfo EXIF_TAG_CODING_METHODS;
    public static final TagInfo EXIF_TAG_COLOR_CHARACTERIZATION;
    public static final TagInfo EXIF_TAG_COLOR_MAP;
    public static final TagInfo EXIF_TAG_COLOR_MATRIX_1;
    public static final TagInfo EXIF_TAG_COLOR_MATRIX_2;
    public static final TagInfo EXIF_TAG_COLOR_RESPONSE_UNIT;
    public static final TagInfo EXIF_TAG_COLOR_SEQUENCE;
    public static final TagInfo EXIF_TAG_COLOR_SPACE;
    public static final TagInfo EXIF_TAG_COLOR_TABLE;
    public static final TagInfo EXIF_TAG_COMPONENTS_CONFIGURATION;
    public static final TagInfo EXIF_TAG_COMPRESSED_BITS_PER_PIXEL;
    public static final TagInfo EXIF_TAG_COMPRESSION;
    public static final TagInfo EXIF_TAG_CONSECUTIVE_BAD_FAX_LINES;
    public static final TagInfo EXIF_TAG_CONTRAST_1;
    public static final TagInfo EXIF_TAG_CONTRAST_2;
    public static final TagInfo EXIF_TAG_CONVERTER;
    public static final TagInfo EXIF_TAG_COPYRIGHT;
    public static final TagInfo EXIF_TAG_CREATE_DATE;
    public static final TagInfo EXIF_TAG_CURRENT_ICCPROFILE;
    public static final TagInfo EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX;
    public static final TagInfo EXIF_TAG_CUSTOM_RENDERED;
    public static final TagInfo EXIF_TAG_DATA_TYPE;
    public static final TagInfo EXIF_TAG_DATE_TIME_ORIGINAL;
    public static final TagInfo EXIF_TAG_DECODE;
    public static final TagInfo EXIF_TAG_DEFAULT_CROP_ORIGIN;
    public static final TagInfo EXIF_TAG_DEFAULT_CROP_SIZE;
    public static final TagInfo EXIF_TAG_DEFAULT_IMAGE_COLOR;
    public static final TagInfo EXIF_TAG_DEFAULT_SCALE;
    public static final TagInfo EXIF_TAG_DEVICE_SETTING_DESCRIPTION;
    public static final TagInfo EXIF_TAG_DIGITAL_ZOOM_RATIO;
    public static final TagInfo EXIF_TAG_DNG_ADOBE_DATA;
    public static final TagInfo EXIF_TAG_DNG_BACKWARD_VERSION;
    public static final TagInfo EXIF_TAG_DNG_LENS_INFO;
    public static final TagInfo EXIF_TAG_DNG_PENTAX_DATA;
    public static final TagInfo EXIF_TAG_DNG_PRIVATE_DATA;
    public static final TagInfo EXIF_TAG_DNG_VERSION;
    public static final TagInfo EXIF_TAG_DOCUMENT_NAME;
    public static final TagInfo EXIF_TAG_DOT_RANGE;
    public static final TagInfo EXIF_TAG_EXIF_IMAGE_LENGTH;
    public static final TagInfo EXIF_TAG_EXIF_IMAGE_WIDTH;
    public static final TagInfo EXIF_TAG_EXIF_OFFSET;
    public static final TagInfo EXIF_TAG_EXIF_VERSION;
    public static final TagInfo EXIF_TAG_EXPOSURE;
    public static final TagInfo EXIF_TAG_EXPOSURE_COMPENSATION;
    public static final TagInfo EXIF_TAG_EXPOSURE_INDEX;
    public static final TagInfo EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD;
    public static final TagInfo EXIF_TAG_EXPOSURE_MODE;
    public static final TagInfo EXIF_TAG_EXPOSURE_PROGRAM;
    public static final TagInfo EXIF_TAG_EXPOSURE_TIME;
    public static final TagInfo EXIF_TAG_EXTRA_SAMPLES;
    public static final TagInfo EXIF_TAG_FAX_PROFILE;
    public static final TagInfo EXIF_TAG_FAX_RECV_PARAMS;
    public static final TagInfo EXIF_TAG_FAX_RECV_TIME;
    public static final TagInfo EXIF_TAG_FAX_SUB_ADDRESS;
    public static final TagInfo EXIF_TAG_FILE_SOURCE;
    public static final TagInfo EXIF_TAG_FILL_ORDER;
    public static final TagInfo EXIF_TAG_FLASH;
    public static final TagInfo EXIF_TAG_FLASHPIX_VERSION;
    public static final TagInfo EXIF_TAG_FLASH_ENERGY;
    public static final TagInfo EXIF_TAG_FLASH_ENERGY_EXIF_IFD;
    public static final TagInfo EXIF_TAG_FNUMBER;
    public static final TagInfo EXIF_TAG_FOCAL_LENGTH;
    public static final TagInfo EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_XRESOLUTION;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_YRESOLUTION;
    public static final TagInfo EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD;
    public static final TagInfo EXIF_TAG_FREE_BYTE_COUNTS;
    public static final TagInfo EXIF_TAG_FREE_OFFSETS;
    public static final TagInfo EXIF_TAG_GAIN_CONTROL;
    public static final TagInfo EXIF_TAG_GAMMA;
    public static final TagInfo EXIF_TAG_GDALMETADATA;
    public static final TagInfo EXIF_TAG_GDALNO_DATA;
    public static final TagInfo EXIF_TAG_GEO_TIFF_ASCII_PARAMS;
    public static final TagInfo EXIF_TAG_GEO_TIFF_DIRECTORY;
    public static final TagInfo EXIF_TAG_GEO_TIFF_DOUBLE_PARAMS;
    public static final TagInfo EXIF_TAG_GLOBAL_PARAMETERS_IFD;
    public static final TagInfo EXIF_TAG_GPSINFO;
    public static final TagInfo EXIF_TAG_GRAY_RESPONSE_CURVE;
    public static final TagInfo EXIF_TAG_GRAY_RESPONSE_UNIT;
    public static final TagInfo EXIF_TAG_HALFTONE_HINTS;
    public static final TagInfo EXIF_TAG_HCUSAGE;
    public static final TagInfo EXIF_TAG_HEIGHT_RESOLUTION;
    public static final TagInfo EXIF_TAG_HOST_COMPUTER;
    public static final TagInfo EXIF_TAG_ICC_PROFILE;
    public static final TagInfo EXIF_TAG_IMAGE_BYTE_COUNT;
    public static final TagInfo EXIF_TAG_IMAGE_COLOR_INDICATOR;
    public static final TagInfo EXIF_TAG_IMAGE_COLOR_VALUE;
    public static final TagInfo EXIF_TAG_IMAGE_DATA_DISCARD;
    public static final TagInfo EXIF_TAG_IMAGE_DEPTH;
    public static final TagInfo EXIF_TAG_IMAGE_DESCRIPTION;
    public static final TagInfo EXIF_TAG_IMAGE_HEIGHT;
    public static final TagInfo EXIF_TAG_IMAGE_HEIGHT_IFD0;
    public static final TagInfo EXIF_TAG_IMAGE_HISTORY;
    public static final TagInfo EXIF_TAG_IMAGE_HISTORY_EXIF_IFD;
    public static final TagInfo EXIF_TAG_IMAGE_ID;
    public static final TagInfo EXIF_TAG_IMAGE_LAYER;
    public static final TagInfo EXIF_TAG_IMAGE_NUMBER;
    public static final TagInfo EXIF_TAG_IMAGE_NUMBER_EXIF_IFD;
    public static final TagInfo EXIF_TAG_IMAGE_OFFSET;
    public static final TagInfo EXIF_TAG_IMAGE_SOURCE_DATA;
    public static final TagInfo EXIF_TAG_IMAGE_TYPE;
    public static final TagInfo EXIF_TAG_IMAGE_UNIQUE_ID;
    public static final TagInfo EXIF_TAG_IMAGE_WIDTH;
    public static final TagInfo EXIF_TAG_IMAGE_WIDTH_IFD0;
    public static final TagInfo EXIF_TAG_INDEXED;
    public static final TagInfo EXIF_TAG_INK_NAMES;
    public static final TagInfo EXIF_TAG_INK_SET;
    public static final TagInfo EXIF_TAG_INTERGRAPH_FLAG_REGISTERS;
    public static final TagInfo EXIF_TAG_INTERGRAPH_MATRIX;
    public static final TagInfo EXIF_TAG_INTERGRAPH_PACKET_DATA;
    public static final TagInfo EXIF_TAG_INTERLACE;
    public static final TagInfo EXIF_TAG_INTEROP_INDEX;
    public static final TagInfo EXIF_TAG_INTEROP_OFFSET;
    public static final TagInfo EXIF_TAG_INTEROP_VERSION;
    public static final TagInfo EXIF_TAG_IPTC_NAA;
    public static final TagInfo EXIF_TAG_ISO;
    public static final TagInfo EXIF_TAG_IT8HEADER;
    public static final TagInfo EXIF_TAG_JPEGACTABLES;
    public static final TagInfo EXIF_TAG_JPEGDCTABLES;
    public static final TagInfo EXIF_TAG_JPEGLOSSLESS_PREDICTORS;
    public static final TagInfo EXIF_TAG_JPEGPOINT_TRANSFORMS;
    public static final TagInfo EXIF_TAG_JPEGPROC;
    public static final TagInfo EXIF_TAG_JPEGQTABLES;
    public static final TagInfo EXIF_TAG_JPEGRESTART_INTERVAL;
    public static final TagInfo EXIF_TAG_JPEGTABLES;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_START_IFD2;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD;
    public static final TagInfo EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2;
    public static final TagInfo EXIF_TAG_LEAF_DATA;
    public static final TagInfo EXIF_TAG_LEAF_SUB_IFD;
    public static final TagInfo EXIF_TAG_LENS;
    public static final TagInfo EXIF_TAG_LIGHT_SOURCE;
    public static final TagInfo EXIF_TAG_LINEARIZATION_TABLE;
    public static final TagInfo EXIF_TAG_LINEAR_RESPONSE_LIMIT;
    public static final TagInfo EXIF_TAG_LOCALIZED_CAMERA_MODEL;
    public static final TagInfo EXIF_TAG_MAKE;
    public static final TagInfo EXIF_TAG_MAKER_NOTE;
    public static final TagInfo EXIF_TAG_MAKER_NOTE_SAFETY;
    public static final TagInfo EXIF_TAG_MASKED_AREAS;
    public static final TagInfo EXIF_TAG_MATTEING;
    public static final TagInfo EXIF_TAG_MAX_APERTURE_VALUE;
    public static final TagInfo EXIF_TAG_MAX_SAMPLE_VALUE;
    public static final TagInfo EXIF_TAG_MDCOLOR_TABLE;
    public static final TagInfo EXIF_TAG_MDFILE_TAG;
    public static final TagInfo EXIF_TAG_MDFILE_UNITS;
    public static final TagInfo EXIF_TAG_MDLAB_NAME;
    public static final TagInfo EXIF_TAG_MDPREP_DATE;
    public static final TagInfo EXIF_TAG_MDPREP_TIME;
    public static final TagInfo EXIF_TAG_MDSAMPLE_INFO;
    public static final TagInfo EXIF_TAG_MDSCALE_PIXEL;
    public static final TagInfo EXIF_TAG_METERING_MODE;
    public static final TagInfo EXIF_TAG_MIN_SAMPLE_VALUE;
    public static final TagInfo EXIF_TAG_MODEL;
    public static final TagInfo EXIF_TAG_MODEL_2;
    public static final TagInfo EXIF_TAG_MODEL_TIE_POINT;
    public static final TagInfo EXIF_TAG_MODEL_TRANSFORM;
    public static final TagInfo EXIF_TAG_MODE_NUMBER;
    public static final TagInfo EXIF_TAG_MODIFY_DATE;
    public static final TagInfo EXIF_TAG_MOIRE_FILTER;
    public static final TagInfo EXIF_TAG_NOISE_1;
    public static final TagInfo EXIF_TAG_NOISE_2;
    public static final TagInfo EXIF_TAG_NUMBEROF_INKS;
    public static final TagInfo EXIF_TAG_OCE_APPLICATION_SELECTOR;
    public static final TagInfo EXIF_TAG_OCE_IDNUMBER;
    public static final TagInfo EXIF_TAG_OCE_IMAGE_LOGIC;
    public static final TagInfo EXIF_TAG_OCE_SCANJOB_DESC;
    public static final TagInfo EXIF_TAG_OFFSET_SCHEMA;
    public static final TagInfo EXIF_TAG_OLD_SUBFILE_TYPE;
    public static final TagInfo EXIF_TAG_OPIPROXY;
    public static final TagInfo EXIF_TAG_OPTO__ELECTRIC_CONV_FACTOR;
    public static final TagInfo EXIF_TAG_ORIENTATION;
    public static final TagInfo EXIF_TAG_ORIGINAL_RAW_FILE_DATA;
    public static final TagInfo EXIF_TAG_ORIGINAL_RAW_FILE_NAME;
    public static final TagInfo EXIF_TAG_OTHER_IMAGE_LENGTH;
    public static final TagInfo EXIF_TAG_OTHER_IMAGE_START;
    public static final TagInfo EXIF_TAG_OWNER_NAME;
    public static final TagInfo EXIF_TAG_PAGE_NAME;
    public static final TagInfo EXIF_TAG_PAGE_NUMBER;
    public static final TagInfo EXIF_TAG_PHOTOMETRIC_INTERPRETATION;
    public static final TagInfo EXIF_TAG_PHOTOSHOP_SETTINGS;
    public static final TagInfo EXIF_TAG_PIXEL_FORMAT;
    public static final TagInfo EXIF_TAG_PIXEL_INTENSITY_RANGE;
    public static final TagInfo EXIF_TAG_PIXEL_SCALE;
    public static final TagInfo EXIF_TAG_PLANAR_CONFIGURATION;
    public static final TagInfo EXIF_TAG_PREDICTOR;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_START_IFD0;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES;
    public static final TagInfo EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1;
    public static final TagInfo EXIF_TAG_PRIMARY_CHROMATICITIES;
    public static final TagInfo EXIF_TAG_PRINT_IM;
    public static final TagInfo EXIF_TAG_PROCESSING_SOFTWARE;
    public static final TagInfo EXIF_TAG_PROFILE_TYPE;
    public static final TagInfo EXIF_TAG_RASTER_PADDING;
    public static final TagInfo EXIF_TAG_RATING;
    public static final TagInfo EXIF_TAG_RATING_PERCENT;
    public static final TagInfo EXIF_TAG_RAW_DATA_UNIQUE_ID;
    public static final TagInfo EXIF_TAG_RAW_FILE;
    public static final TagInfo EXIF_TAG_REDUCTION_MATRIX_1;
    public static final TagInfo EXIF_TAG_REDUCTION_MATRIX_2;
    public static final TagInfo EXIF_TAG_REFERENCE_BLACK_WHITE;
    public static final TagInfo EXIF_TAG_RELATED_IMAGE_FILE_FORMAT;
    public static final TagInfo EXIF_TAG_RELATED_IMAGE_LENGTH;
    public static final TagInfo EXIF_TAG_RELATED_IMAGE_WIDTH;
    public static final TagInfo EXIF_TAG_RELATED_SOUND_FILE;
    public static final TagInfo EXIF_TAG_RESOLUTION_UNIT;
    public static final TagInfo EXIF_TAG_ROWS_PER_STRIP;
    public static final TagInfo EXIF_TAG_SAMPLES_PER_PIXEL;
    public static final TagInfo EXIF_TAG_SAMPLE_FORMAT;
    public static final TagInfo EXIF_TAG_SATURATION_1;
    public static final TagInfo EXIF_TAG_SATURATION_2;
    public static final TagInfo EXIF_TAG_SCENE_CAPTURE_TYPE;
    public static final TagInfo EXIF_TAG_SCENE_TYPE;
    public static final TagInfo EXIF_TAG_SECURITY_CLASSIFICATION;
    public static final TagInfo EXIF_TAG_SECURITY_CLASSIFICATION_EXIF_IFD;
    public static final TagInfo EXIF_TAG_SELF_TIMER_MODE;
    public static final TagInfo EXIF_TAG_SEMINFO;
    public static final TagInfo EXIF_TAG_SENSING_METHOD;
    public static final TagInfo EXIF_TAG_SENSING_METHOD_EXIF_IFD;
    public static final TagInfo EXIF_TAG_SERIAL_NUMBER;
    public static final TagInfo EXIF_TAG_SHADOWS;
    public static final TagInfo EXIF_TAG_SHADOW_SCALE;
    public static final TagInfo EXIF_TAG_SHARPNESS_1;
    public static final TagInfo EXIF_TAG_SHARPNESS_2;
    public static final TagInfo EXIF_TAG_SHUTTER_SPEED_VALUE;
    public static final TagInfo EXIF_TAG_SITE;
    public static final TagInfo EXIF_TAG_SMAX_SAMPLE_VALUE;
    public static final TagInfo EXIF_TAG_SMIN_SAMPLE_VALUE;
    public static final TagInfo EXIF_TAG_SMOOTHNESS;
    public static final TagInfo EXIF_TAG_SOFTWARE;
    public static final TagInfo EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_1;
    public static final TagInfo EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2;
    public static final TagInfo EXIF_TAG_SPECTRAL_SENSITIVITY;
    public static final TagInfo EXIF_TAG_STO_NITS;
    public static final TagInfo EXIF_TAG_STRIP_ROW_COUNTS;
    public static final TagInfo EXIF_TAG_SUBFILE_TYPE;
    public static final TagInfo EXIF_TAG_SUBJECT_DISTANCE;
    public static final TagInfo EXIF_TAG_SUBJECT_DISTANCE_RANGE;
    public static final TagInfo EXIF_TAG_SUBJECT_LOCATION_1;
    public static final TagInfo EXIF_TAG_SUBJECT_LOCATION_2;
    public static final TagInfo EXIF_TAG_SUB_IFD;
    public static final TagInfo EXIF_TAG_SUB_SEC_TIME;
    public static final TagInfo EXIF_TAG_SUB_SEC_TIME_DIGITIZED;
    public static final TagInfo EXIF_TAG_SUB_SEC_TIME_ORIGINAL;
    public static final TagInfo EXIF_TAG_T4OPTIONS;
    public static final TagInfo EXIF_TAG_T6OPTIONS;
    public static final TagInfo EXIF_TAG_TARGET_PRINTER;
    public static final TagInfo EXIF_TAG_THRESHOLDING;
    public static final TagInfo EXIF_TAG_TIFF_EPSTANDARD_ID_1;
    public static final TagInfo EXIF_TAG_TIFF_EPSTANDARD_ID_2;
    public static final TagInfo EXIF_TAG_TILE_BYTE_COUNTS;
    public static final TagInfo EXIF_TAG_TILE_DEPTH;
    public static final TagInfo EXIF_TAG_TILE_LENGTH;
    public static final TagInfo EXIF_TAG_TILE_OFFSETS;
    public static final TagInfo EXIF_TAG_TILE_WIDTH;
    public static final TagInfo EXIF_TAG_TIME_ZONE_OFFSET;
    public static final TagInfo EXIF_TAG_TRANSFER_FUNCTION;
    public static final TagInfo EXIF_TAG_TRANSFER_RANGE;
    public static final TagInfo EXIF_TAG_TRANSFOMATION;
    public static final TagInfo EXIF_TAG_TRANSPARENCY_INDICATOR;
    public static final TagInfo EXIF_TAG_UNCOMPRESSED;
    public static final TagInfo EXIF_TAG_UNIQUE_CAMERA_MODEL;
    public static final TagInfo EXIF_TAG_USER_COMMENT;
    public static final TagInfo EXIF_TAG_VERSION_YEAR;
    public static final TagInfo EXIF_TAG_WANG_ANNOTATION;
    public static final TagInfo EXIF_TAG_WHITE_BALANCE_1;
    public static final TagInfo EXIF_TAG_WHITE_BALANCE_2;
    public static final TagInfo EXIF_TAG_WHITE_LEVEL;
    public static final TagInfo EXIF_TAG_WHITE_POINT;
    public static final TagInfo EXIF_TAG_WIDTH_RESOLUTION;
    public static final TagInfo EXIF_TAG_XCLIP_PATH_UNITS;
    public static final TagInfo EXIF_TAG_XPAUTHOR;
    public static final TagInfo EXIF_TAG_XPCOMMENT;
    public static final TagInfo EXIF_TAG_XPKEYWORDS;
    public static final TagInfo EXIF_TAG_XPOSITION;
    public static final TagInfo EXIF_TAG_XPSUBJECT;
    public static final TagInfo EXIF_TAG_XPTITLE;
    public static final TagInfo EXIF_TAG_XRESOLUTION;
    public static final TagInfo EXIF_TAG_YCBCR_COEFFICIENTS;
    public static final TagInfo EXIF_TAG_YCBCR_POSITIONING;
    public static final TagInfo EXIF_TAG_YCBCR_SUB_SAMPLING;
    public static final TagInfo EXIF_TAG_YCLIP_PATH_UNITS;
    public static final TagInfo EXIF_TAG_YPOSITION;
    public static final TagInfo EXIF_TAG_YRESOLUTION;

    static {
        TagInfo tagInfo = new TagInfo("Interop Index", 1, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_INTEROP_INDEX = tagInfo;
        TagInfo tagInfo2 = new TagInfo("Interop Version", 2, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_INTEROP_VERSION = tagInfo2;
        TagInfo tagInfo3 = new TagInfo("Processing Software", 11, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PROCESSING_SOFTWARE = tagInfo3;
        TagInfo tagInfo4 = new TagInfo("Subfile Type", 254, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SUBFILE_TYPE = tagInfo4;
        TagInfo tagInfo5 = new TagInfo("Old Subfile Type", 255, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_OLD_SUBFILE_TYPE = tagInfo5;
        TagInfo tagInfo6 = new TagInfo("Image Width", 256, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IMAGE_WIDTH_IFD0 = tagInfo6;
        TagInfo tagInfo7 = new TagInfo("Image Height", 257, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IMAGE_HEIGHT_IFD0 = tagInfo7;
        TagInfo tagInfo8 = new TagInfo("Bits Per Sample", 258, (FieldType) FIELD_TYPE_SHORT, -1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BITS_PER_SAMPLE = tagInfo8;
        TagInfo tagInfo9 = new TagInfo("Compression", 259, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_COMPRESSION = tagInfo9;
        TagInfo tagInfo10 = new TagInfo("Photometric Interpretation", (int) ResultCodes.ERROR_OTHER, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PHOTOMETRIC_INTERPRETATION = tagInfo10;
        TagInfo tagInfo11 = new TagInfo("Thresholding", 263, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_THRESHOLDING = tagInfo11;
        TagInfo tagInfo12 = new TagInfo("Cell Width", 264, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CELL_WIDTH = tagInfo12;
        TagInfo tagInfo13 = new TagInfo("Cell Length", 265, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CELL_LENGTH = tagInfo13;
        TagInfo tagInfo14 = new TagInfo("Fill Order", 266, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_FILL_ORDER = tagInfo14;
        TagInfo tagInfo15 = new TagInfo("Document Name", 269, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DOCUMENT_NAME = tagInfo15;
        TagInfo tagInfo16 = new TagInfo("Image Description", 270, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IMAGE_DESCRIPTION = tagInfo16;
        TagInfo tagInfo17 = new TagInfo("Make", 271, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MAKE = tagInfo17;
        TagInfo tagInfo18 = new TagInfo("Model", 272, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MODEL = tagInfo18;
        Offset offset = new Offset("Preview Image Start", 273, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREVIEW_IMAGE_START_IFD0 = offset;
        Offset offset2 = new Offset("Preview Image Start", 273, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD1);
        EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1 = offset2;
        Offset offset3 = new Offset("Jpg From Raw Start", 273, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD2);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2 = offset3;
        TagInfo tagInfo19 = new TagInfo("Orientation", 274, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIENTATION = tagInfo19;
        TagInfo tagInfo20 = new TagInfo("Samples Per Pixel", 277, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SAMPLES_PER_PIXEL = tagInfo20;
        TagInfo tagInfo21 = new TagInfo("Rows Per Strip", 278, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ROWS_PER_STRIP = tagInfo21;
        TagInfo tagInfo22 = new TagInfo("Preview Image Length", 279, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0 = tagInfo22;
        TagInfo tagInfo23 = new TagInfo("Preview Image Length", 279, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD1);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1 = tagInfo23;
        TagInfo tagInfo24 = new TagInfo("Jpg From Raw Length", 279, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD2);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2 = tagInfo24;
        TagInfo tagInfo25 = new TagInfo("Min Sample Value", 280, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MIN_SAMPLE_VALUE = tagInfo25;
        TagInfo tagInfo26 = new TagInfo("Max Sample Value", 281, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MAX_SAMPLE_VALUE = tagInfo26;
        TagInfo tagInfo27 = new TagInfo("XResolution", 282, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XRESOLUTION = tagInfo27;
        TagInfo tagInfo28 = new TagInfo("YResolution", 283, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_YRESOLUTION = tagInfo28;
        TagInfo tagInfo29 = new TagInfo("Planar Configuration", 284, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PLANAR_CONFIGURATION = tagInfo29;
        TagInfo tagInfo30 = new TagInfo("Page Name", 285, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PAGE_NAME = tagInfo30;
        TagInfo tagInfo31 = new TagInfo("XPosition", 286, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPOSITION = tagInfo31;
        TagInfo tagInfo32 = new TagInfo("YPosition", 287, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_YPOSITION = tagInfo32;
        TagInfo tagInfo33 = new TagInfo("Free Offsets", 288, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FREE_OFFSETS = tagInfo33;
        TagInfo tagInfo34 = new TagInfo("Free Byte Counts", 289, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FREE_BYTE_COUNTS = tagInfo34;
        TagInfo tagInfo35 = new TagInfo("Gray Response Unit", 290, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_GRAY_RESPONSE_UNIT = tagInfo35;
        TagInfo tagInfo36 = new TagInfo("Gray Response Curve", 291, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GRAY_RESPONSE_CURVE = tagInfo36;
        TagInfo tagInfo37 = new TagInfo("T4 Options", 292, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_T4OPTIONS = tagInfo37;
        TagInfo tagInfo38 = new TagInfo("T6 Options", 293, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_T6OPTIONS = tagInfo38;
        TagInfo tagInfo39 = new TagInfo("Resolution Unit", 296, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_RESOLUTION_UNIT = tagInfo39;
        TagInfo tagInfo40 = new TagInfo("Page Number", 297, (FieldType) FIELD_TYPE_SHORT, 2, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PAGE_NUMBER = tagInfo40;
        TagInfo tagInfo41 = new TagInfo("Color Response Unit", (int) LogSeverity.NOTICE_VALUE, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_RESPONSE_UNIT = tagInfo41;
        TagInfo tagInfo42 = new TagInfo("Transfer Function", 301, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSFER_FUNCTION = tagInfo42;
        TagInfo tagInfo43 = new TagInfo("Software", 305, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SOFTWARE = tagInfo43;
        TagInfo tagInfo44 = new TagInfo("Modify Date", 306, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MODIFY_DATE = tagInfo44;
        TagInfo tagInfo45 = new TagInfo("Artist", 315, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ARTIST = tagInfo45;
        TagInfo tagInfo46 = new TagInfo("Host Computer", 316, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_HOST_COMPUTER = tagInfo46;
        TagInfo tagInfo47 = new TagInfo("Predictor", 317, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREDICTOR = tagInfo47;
        TagInfo tagInfo48 = new TagInfo("White Point", 318, (FieldType) FIELD_TYPE_RATIONAL, 2, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_WHITE_POINT = tagInfo48;
        TagInfo tagInfo49 = new TagInfo("Primary Chromaticities", 319, (FieldType) FIELD_TYPE_RATIONAL, 6, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PRIMARY_CHROMATICITIES = tagInfo49;
        TagInfo tagInfo50 = new TagInfo("Color Map", (int) ModuleDescriptor.MODULE_VERSION, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_MAP = tagInfo50;
        TagInfo tagInfo51 = new TagInfo("Halftone Hints", 321, (FieldType) FIELD_TYPE_SHORT, 2, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_HALFTONE_HINTS = tagInfo51;
        TagInfo tagInfo52 = new TagInfo("Tile Width", 322, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_TILE_WIDTH = tagInfo52;
        TagInfo tagInfo53 = new TagInfo("Tile Length", 323, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_TILE_LENGTH = tagInfo53;
        TagInfo tagInfo54 = new TagInfo("Tile Offsets", 324, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TILE_OFFSETS = tagInfo54;
        TagInfo tagInfo55 = new TagInfo("Tile Byte Counts", 325, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TILE_BYTE_COUNTS = tagInfo55;
        TagInfo tagInfo56 = new TagInfo("Bad Fax Lines", 326, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BAD_FAX_LINES = tagInfo56;
        TagInfo tagInfo57 = new TagInfo("Clean Fax Data", 327, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CLEAN_FAX_DATA = tagInfo57;
        TagInfo tagInfo58 = new TagInfo("Consecutive Bad Fax Lines", 328, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CONSECUTIVE_BAD_FAX_LINES = tagInfo58;
        TagInfo tagInfo59 = new TagInfo("Sub IFD", 330, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SUB_IFD = tagInfo59;
        TagInfo tagInfo60 = new TagInfo("Ink Set", 332, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_INK_SET = tagInfo60;
        TagInfo tagInfo61 = new TagInfo("Ink Names", 333, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INK_NAMES = tagInfo61;
        TagInfo tagInfo62 = new TagInfo("Numberof Inks", 334, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NUMBEROF_INKS = tagInfo62;
        TagInfo tagInfo63 = new TagInfo("Dot Range", 336, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DOT_RANGE = tagInfo63;
        TagInfo tagInfo64 = new TagInfo("Target Printer", 337, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TARGET_PRINTER = tagInfo64;
        TagInfo tagInfo65 = new TagInfo("Extra Samples", 338, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXTRA_SAMPLES = tagInfo65;
        TagInfo tagInfo66 = new TagInfo("Sample Format", 339, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SAMPLE_FORMAT = tagInfo66;
        TagInfo tagInfo67 = new TagInfo("SMin Sample Value", 340, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SMIN_SAMPLE_VALUE = tagInfo67;
        TagInfo tagInfo68 = new TagInfo("SMax Sample Value", (int) FacebookRequestErrorClassification.EC_TOO_MANY_USER_ACTION_CALLS, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SMAX_SAMPLE_VALUE = tagInfo68;
        TagInfo tagInfo69 = new TagInfo("Transfer Range", 342, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSFER_RANGE = tagInfo69;
        TagInfo tagInfo70 = new TagInfo("Clip Path", 343, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CLIP_PATH = tagInfo70;
        TagInfo tagInfo71 = new TagInfo("XClip Path Units", 344, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_XCLIP_PATH_UNITS = tagInfo71;
        TagInfo tagInfo72 = new TagInfo("YClip Path Units", 345, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_YCLIP_PATH_UNITS = tagInfo72;
        TagInfo tagInfo73 = new TagInfo("Indexed", 346, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INDEXED = tagInfo73;
        TagInfo tagInfo74 = new TagInfo("JPEGTables", 347, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGTABLES = tagInfo74;
        TagInfo tagInfo75 = new TagInfo("OPIProxy", 351, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPIPROXY = tagInfo75;
        TagInfo tagInfo76 = new TagInfo("Global Parameters IFD", (int) LogSeverity.WARNING_VALUE, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GLOBAL_PARAMETERS_IFD = tagInfo76;
        TagInfo tagInfo77 = new TagInfo("Profile Type", 401, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PROFILE_TYPE = tagInfo77;
        TagInfo tagInfo78 = new TagInfo("Fax Profile", 402, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FAX_PROFILE = tagInfo78;
        TagInfo tagInfo79 = new TagInfo("Coding Methods", 403, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CODING_METHODS = tagInfo79;
        TagInfo tagInfo80 = new TagInfo("Version Year", (int) HttpStatus.HTTP_NOT_FOUND, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_VERSION_YEAR = tagInfo80;
        TagInfo tagInfo81 = new TagInfo("Mode Number", 405, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODE_NUMBER = tagInfo81;
        TagInfo tagInfo82 = new TagInfo("Decode", 433, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DECODE = tagInfo82;
        TagInfo tagInfo83 = new TagInfo("Default Image Color", 434, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEFAULT_IMAGE_COLOR = tagInfo83;
        TagInfo tagInfo84 = new TagInfo("JPEGProc", 512, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGPROC = tagInfo84;
        TagInfo tagInfo85 = new TagInfo("Preview Image Start", (int) SASocket.CONNECTION_LOST_PEER_DISCONNECTED, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES = tagInfo85;
        Offset offset4 = new Offset("Jpg From Raw Start", (int) SASocket.CONNECTION_LOST_PEER_DISCONNECTED, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD = offset4;
        Offset offset5 = new Offset("Jpg From Raw Start", (int) SASocket.CONNECTION_LOST_PEER_DISCONNECTED, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD2);
        EXIF_TAG_JPG_FROM_RAW_START_IFD2 = offset5;
        Offset offset6 = new Offset("Other Image Start", (int) SASocket.CONNECTION_LOST_PEER_DISCONNECTED, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OTHER_IMAGE_START = offset6;
        TagInfo tagInfo86 = new TagInfo("Preview Image Length", 514, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES = tagInfo86;
        TagInfo tagInfo87 = new TagInfo("Jpg From Raw Length", 514, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD = tagInfo87;
        TagInfo tagInfo88 = new TagInfo("Jpg From Raw Length", 514, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD2);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2 = tagInfo88;
        TagInfo tagInfo89 = new TagInfo("Other Image Length", 514, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OTHER_IMAGE_LENGTH = tagInfo89;
        TagInfo tagInfo90 = new TagInfo("JPEGRestart Interval", 515, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGRESTART_INTERVAL = tagInfo90;
        TagInfo tagInfo91 = new TagInfo("JPEGLossless Predictors", 517, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGLOSSLESS_PREDICTORS = tagInfo91;
        TagInfo tagInfo92 = new TagInfo("JPEGPoint Transforms", 518, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGPOINT_TRANSFORMS = tagInfo92;
        TagInfo tagInfo93 = new TagInfo("JPEGQTables", 519, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGQTABLES = tagInfo93;
        TagInfo tagInfo94 = new TagInfo("JPEGDCTables", 520, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGDCTABLES = tagInfo94;
        TagInfo tagInfo95 = new TagInfo("JPEGACTables", (int) SASocket.CONNECTION_LOST_DEVICE_DETACHED, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_JPEGACTABLES = tagInfo95;
        TagInfo tagInfo96 = new TagInfo("YCbCr Coefficients", 529, (FieldType) FIELD_TYPE_RATIONAL, 3, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_YCBCR_COEFFICIENTS = tagInfo96;
        TagInfo tagInfo97 = new TagInfo("YCbCr Sub Sampling", 530, (FieldType) FIELD_TYPE_SHORT, 2, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_YCBCR_SUB_SAMPLING = tagInfo97;
        TagInfo tagInfo98 = new TagInfo("YCbCr Positioning", 531, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_YCBCR_POSITIONING = tagInfo98;
        TagInfo tagInfo99 = new TagInfo("Reference Black White", 532, (FieldType) FIELD_TYPE_RATIONAL, 6, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_REFERENCE_BLACK_WHITE = tagInfo99;
        TagInfo tagInfo100 = new TagInfo("Strip Row Counts", 559, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_STRIP_ROW_COUNTS = tagInfo100;
        TagInfo tagInfo101 = new TagInfo("Application Notes", (int) LogSeverity.ALERT_VALUE, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_APPLICATION_NOTES = tagInfo101;
        TagInfo tagInfo102 = new TagInfo("Related Image File Format", 4096, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_RELATED_IMAGE_FILE_FORMAT = tagInfo102;
        TagInfo tagInfo103 = new TagInfo("Related Image Width", (int) FragmentTransaction.TRANSIT_FRAGMENT_OPEN, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_RELATED_IMAGE_WIDTH = tagInfo103;
        TagInfo tagInfo104 = new TagInfo("Related Image Length", 4098, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_RELATED_IMAGE_LENGTH = tagInfo104;
        TagInfo tagInfo105 = new TagInfo("Rating", 18246, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_RATING = tagInfo105;
        TagInfo tagInfo106 = new TagInfo("Rating Percent", 18249, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_RATING_PERCENT = tagInfo106;
        TagInfo tagInfo107 = new TagInfo("Image ID", 32781, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_ID = tagInfo107;
        TagInfo tagInfo108 = new TagInfo("Wang Annotation", 32932, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_WANG_ANNOTATION = tagInfo108;
        TagInfo tagInfo109 = new TagInfo("Matteing", 32995, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MATTEING = tagInfo109;
        TagInfo tagInfo110 = new TagInfo("Data Type", 32996, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DATA_TYPE = tagInfo110;
        TagInfo tagInfo111 = new TagInfo("Image Depth", 32997, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_DEPTH = tagInfo111;
        TagInfo tagInfo112 = new TagInfo("Tile Depth", 32998, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TILE_DEPTH = tagInfo112;
        TagInfo tagInfo113 = new TagInfo("Model 2", 33405, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODEL_2 = tagInfo113;
        TagInfo tagInfo114 = new TagInfo("CFARepeat Pattern Dim", 33421, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CFAREPEAT_PATTERN_DIM = tagInfo114;
        TagInfo tagInfo115 = new TagInfo("CFAPattern 2", 33422, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CFAPATTERN_2 = tagInfo115;
        TagInfo tagInfo116 = new TagInfo("Battery Level", 33423, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BATTERY_LEVEL = tagInfo116;
        TagInfo tagInfo117 = new TagInfo("Copyright", 33432, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_COPYRIGHT = tagInfo117;
        TagInfo tagInfo118 = new TagInfo("Exposure Time", 33434, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_TIME = tagInfo118;
        TagInfo tagInfo119 = new TagInfo("FNumber", 33437, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FNUMBER = tagInfo119;
        TagInfo tagInfo120 = new TagInfo("MDFile Tag", 33445, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDFILE_TAG = tagInfo120;
        TagInfo tagInfo121 = new TagInfo("MDScale Pixel", 33446, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDSCALE_PIXEL = tagInfo121;
        TagInfo tagInfo122 = new TagInfo("MDColor Table", 33447, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDCOLOR_TABLE = tagInfo122;
        TagInfo tagInfo123 = new TagInfo("MDLab Name", 33448, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDLAB_NAME = tagInfo123;
        TagInfo tagInfo124 = new TagInfo("MDSample Info", 33449, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDSAMPLE_INFO = tagInfo124;
        TagInfo tagInfo125 = new TagInfo("MDPrep Date", 33450, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDPREP_DATE = tagInfo125;
        TagInfo tagInfo126 = new TagInfo("MDPrep Time", 33451, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDPREP_TIME = tagInfo126;
        TagInfo tagInfo127 = new TagInfo("MDFile Units", 33452, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MDFILE_UNITS = tagInfo127;
        TagInfo tagInfo128 = new TagInfo("Pixel Scale", 33550, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_SCALE = tagInfo128;
        TagInfo tagInfo129 = new TagInfo("IPTC- NAA", 33723, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IPTC_NAA = tagInfo129;
        TagInfo tagInfo130 = new TagInfo("Intergraph Packet Data", 33918, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_PACKET_DATA = tagInfo130;
        TagInfo tagInfo131 = new TagInfo("Intergraph Flag Registers", 33919, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_FLAG_REGISTERS = tagInfo131;
        TagInfo tagInfo132 = new TagInfo("Intergraph Matrix", 33920, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_MATRIX = tagInfo132;
        TagInfo tagInfo133 = new TagInfo("Model Tie Point", 33922, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODEL_TIE_POINT = tagInfo133;
        TagInfo tagInfo134 = new TagInfo("Site", 34016, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SITE = tagInfo134;
        TagInfo tagInfo135 = new TagInfo("Color Sequence", 34017, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_SEQUENCE = tagInfo135;
        TagInfo tagInfo136 = new TagInfo("IT8 Header", 34018, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IT8HEADER = tagInfo136;
        TagInfo tagInfo137 = new TagInfo("Raster Padding", 34019, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_RASTER_PADDING = tagInfo137;
        TagInfo tagInfo138 = new TagInfo("Bits Per Run Length", 34020, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_RUN_LENGTH = tagInfo138;
        TagInfo tagInfo139 = new TagInfo("Bits Per Extended Run Length", 34021, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH = tagInfo139;
        TagInfo tagInfo140 = new TagInfo("Color Table", 34022, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_TABLE = tagInfo140;
        TagInfo tagInfo141 = new TagInfo("Image Color Indicator", 34023, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_INDICATOR = tagInfo141;
        TagInfo tagInfo142 = new TagInfo("Background Color Indicator", 34024, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_INDICATOR = tagInfo142;
        TagInfo tagInfo143 = new TagInfo("Image Color Value", 34025, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_VALUE = tagInfo143;
        TagInfo tagInfo144 = new TagInfo("Background Color Value", 34026, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_VALUE = tagInfo144;
        TagInfo tagInfo145 = new TagInfo("Pixel Intensity Range", 34027, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_INTENSITY_RANGE = tagInfo145;
        TagInfo tagInfo146 = new TagInfo("Transparency Indicator", 34028, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSPARENCY_INDICATOR = tagInfo146;
        TagInfo tagInfo147 = new TagInfo("Color Characterization", 34029, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_CHARACTERIZATION = tagInfo147;
        TagInfo tagInfo148 = new TagInfo("HCUsage", 34030, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_HCUSAGE = tagInfo148;
        TagInfo tagInfo149 = new TagInfo("SEMInfo", 34118, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SEMINFO = tagInfo149;
        TagInfo tagInfo150 = new TagInfo("AFCP_ IPTC", 34152, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AFCP_IPTC = tagInfo150;
        TagInfo tagInfo151 = new TagInfo("Model Transform", 34264, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODEL_TRANSFORM = tagInfo151;
        TagInfo tagInfo152 = new TagInfo("Leaf Data", 34310, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_DATA = tagInfo152;
        TagInfo tagInfo153 = new TagInfo("Photoshop Settings", 34377, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PHOTOSHOP_SETTINGS = tagInfo153;
        Offset offset7 = new Offset("Exif Offset", 34665, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXIF_OFFSET = offset7;
        TagInfo tagInfo154 = new TagInfo("ICC_ Profile", 34675, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ICC_PROFILE = tagInfo154;
        TagInfo tagInfo155 = new TagInfo("Image Layer", 34732, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_LAYER = tagInfo155;
        TagInfo tagInfo156 = new TagInfo("Geo Tiff Directory", 34735, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GEO_TIFF_DIRECTORY = tagInfo156;
        TagInfo tagInfo157 = new TagInfo("Geo Tiff Double Params", 34736, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GEO_TIFF_DOUBLE_PARAMS = tagInfo157;
        TagInfo tagInfo158 = new TagInfo("Geo Tiff Ascii Params", 34737, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GEO_TIFF_ASCII_PARAMS = tagInfo158;
        TagInfo tagInfo159 = new TagInfo("Exposure Program", 34850, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_PROGRAM = tagInfo159;
        TagInfo tagInfo160 = new TagInfo("Spectral Sensitivity", 34852, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SPECTRAL_SENSITIVITY = tagInfo160;
        Offset offset8 = new Offset("GPSInfo", 34853, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GPSINFO = offset8;
        TagInfo tagInfo161 = new TagInfo("ISO", 34855, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_ISO = tagInfo161;
        TagInfo tagInfo162 = new TagInfo("Opto - Electric Conv Factor", 34856, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OPTO__ELECTRIC_CONV_FACTOR = tagInfo162;
        TagInfo tagInfo163 = new TagInfo("Interlace", 34857, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERLACE = tagInfo163;
        TagInfo tagInfo164 = new TagInfo("Time Zone Offset", 34858, FIELD_TYPE_SSHORT, -1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_TIME_ZONE_OFFSET = tagInfo164;
        TagInfo tagInfo165 = new TagInfo("Self Timer Mode", 34859, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SELF_TIMER_MODE = tagInfo165;
        TagInfo tagInfo166 = new TagInfo("Fax Recv Params", 34908, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FAX_RECV_PARAMS = tagInfo166;
        TagInfo tagInfo167 = new TagInfo("Fax Sub Address", 34909, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FAX_SUB_ADDRESS = tagInfo167;
        TagInfo tagInfo168 = new TagInfo("Fax Recv Time", 34910, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FAX_RECV_TIME = tagInfo168;
        TagInfo tagInfo169 = new TagInfo("Leaf Sub IFD", 34954, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_SUB_IFD = tagInfo169;
        TagInfo tagInfo170 = new TagInfo("Exif Version", 36864, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_VERSION = tagInfo170;
        TagInfo tagInfo171 = new TagInfo("Date Time Original", 36867, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DATE_TIME_ORIGINAL = tagInfo171;
        TagInfo tagInfo172 = new TagInfo("Create Date", 36868, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CREATE_DATE = tagInfo172;
        TagInfo tagInfo173 = new TagInfo("Components Configuration", 37121, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPONENTS_CONFIGURATION = tagInfo173;
        TagInfo tagInfo174 = new TagInfo("Compressed Bits Per Pixel", 37122, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPRESSED_BITS_PER_PIXEL = tagInfo174;
        TagInfo tagInfo175 = new TagInfo("Shutter Speed Value", 37377, FIELD_TYPE_SRATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHUTTER_SPEED_VALUE = tagInfo175;
        TagInfo tagInfo176 = new TagInfo("Aperture Value", 37378, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_APERTURE_VALUE = tagInfo176;
        TagInfo tagInfo177 = new TagInfo("Brightness Value", 37379, FIELD_TYPE_SRATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS_VALUE = tagInfo177;
        TagInfo tagInfo178 = new TagInfo("Exposure Compensation", 37380, FIELD_TYPE_SRATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_COMPENSATION = tagInfo178;
        TagInfo tagInfo179 = new TagInfo("Max Aperture Value", 37381, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MAX_APERTURE_VALUE = tagInfo179;
        TagInfo tagInfo180 = new TagInfo("Subject Distance", 37382, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_DISTANCE = tagInfo180;
        TagInfo tagInfo181 = new TagInfo("Metering Mode", 37383, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_METERING_MODE = tagInfo181;
        TagInfo tagInfo182 = new TagInfo("Light Source", 37384, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LIGHT_SOURCE = tagInfo182;
        TagInfo tagInfo183 = new TagInfo("Flash", 37385, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASH = tagInfo183;
        TagInfo tagInfo184 = new TagInfo("Focal Length", 37386, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH = tagInfo184;
        TagInfo tagInfo185 = new TagInfo("Flash Energy", 37387, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FLASH_ENERGY = tagInfo185;
        TagInfo tagInfo186 = new TagInfo("Spatial Frequency Response", 37388, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_1 = tagInfo186;
        TagInfo tagInfo187 = new TagInfo("Noise", 37389, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NOISE_1 = tagInfo187;
        TagInfo tagInfo188 = new TagInfo("Focal Plane XResolution", 37390, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FOCAL_PLANE_XRESOLUTION = tagInfo188;
        TagInfo tagInfo189 = new TagInfo("Focal Plane YResolution", 37391, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FOCAL_PLANE_YRESOLUTION = tagInfo189;
        TagInfo tagInfo190 = new TagInfo("Focal Plane Resolution Unit", 37392, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT = tagInfo190;
        TagInfo tagInfo191 = new TagInfo("Image Number", 37393, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_NUMBER_EXIF_IFD = tagInfo191;
        TagInfo tagInfo192 = new TagInfo("Security Classification", 37394, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SECURITY_CLASSIFICATION_EXIF_IFD = tagInfo192;
        TagInfo tagInfo193 = new TagInfo("Image History", 37395, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_HISTORY_EXIF_IFD = tagInfo193;
        TagInfo tagInfo194 = new TagInfo("Subject Location", 37396, (FieldType) FIELD_TYPE_SHORT, 4, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_LOCATION_1 = tagInfo194;
        TagInfo tagInfo195 = new TagInfo("Exposure Index", 37397, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXPOSURE_INDEX = tagInfo195;
        TagInfo tagInfo196 = new TagInfo("TIFF- EPStandard ID", 37398, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TIFF_EPSTANDARD_ID_1 = tagInfo196;
        TagInfo tagInfo197 = new TagInfo("Sensing Method", 37399, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SENSING_METHOD = tagInfo197;
        TagInfo tagInfo198 = new TagInfo("Sto Nits", 37439, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_STO_NITS = tagInfo198;
        TagInfo tagInfo199 = new TagInfo("Maker Note", 37500, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MAKER_NOTE = tagInfo199;
        Text text = new Text("UserComment", 37510, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_USER_COMMENT = text;
        TagInfo tagInfo200 = new TagInfo("Sub Sec Time", 37520, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME = tagInfo200;
        TagInfo tagInfo201 = new TagInfo("Sub Sec Time Original", 37521, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_ORIGINAL = tagInfo201;
        TagInfo tagInfo202 = new TagInfo("Sub Sec Time Digitized", 37522, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_DIGITIZED = tagInfo202;
        TagInfo tagInfo203 = new TagInfo("Image Source Data", 37724, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_IMAGE_SOURCE_DATA = tagInfo203;
        TagInfo tagInfo204 = new TagInfo("XPTitle", 40091, (FieldType) FIELD_TYPE_BYTE, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPTITLE = tagInfo204;
        TagInfo tagInfo205 = new TagInfo("XPComment", 40092, (FieldType) FIELD_TYPE_BYTE, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPCOMMENT = tagInfo205;
        TagInfo tagInfo206 = new TagInfo("XPAuthor", 40093, (FieldType) FIELD_TYPE_BYTE, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPAUTHOR = tagInfo206;
        TagInfo tagInfo207 = new TagInfo("XPKeywords", 40094, (FieldType) FIELD_TYPE_BYTE, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPKEYWORDS = tagInfo207;
        TagInfo tagInfo208 = new TagInfo("XPSubject", 40095, (FieldType) FIELD_TYPE_BYTE, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_XPSUBJECT = tagInfo208;
        TagInfo tagInfo209 = new TagInfo("Flashpix Version", 40960, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASHPIX_VERSION = tagInfo209;
        TagInfo tagInfo210 = new TagInfo("Color Space", 40961, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COLOR_SPACE = tagInfo210;
        TagInfo tagInfo211 = new TagInfo("Exif Image Width", 40962, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_WIDTH = tagInfo211;
        TagInfo tagInfo212 = new TagInfo("Exif Image Length", 40963, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_LENGTH = tagInfo212;
        TagInfo tagInfo213 = new TagInfo("Related Sound File", 40964, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RELATED_SOUND_FILE = tagInfo213;
        Offset offset9 = new Offset("Interop Offset", 40965, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTEROP_OFFSET = offset9;
        TagInfo tagInfo214 = new TagInfo("Flash Energy", 41483, (FieldType) FIELD_TYPE_RATIONAL, -1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASH_ENERGY_EXIF_IFD = tagInfo214;
        TagInfo tagInfo215 = new TagInfo("Spatial Frequency Response", 41484, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2 = tagInfo215;
        TagInfo tagInfo216 = new TagInfo("Noise", 41485, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NOISE_2 = tagInfo216;
        TagInfo tagInfo217 = new TagInfo("Focal Plane XResolution", 41486, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD = tagInfo217;
        TagInfo tagInfo218 = new TagInfo("Focal Plane YResolution", 41487, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD = tagInfo218;
        TagInfo tagInfo219 = new TagInfo("Focal Plane Resolution Unit", 41488, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD = tagInfo219;
        TagInfo tagInfo220 = new TagInfo("Image Number", 41489, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_NUMBER = tagInfo220;
        TagInfo tagInfo221 = new TagInfo("Security Classification", 41490, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SECURITY_CLASSIFICATION = tagInfo221;
        TagInfo tagInfo222 = new TagInfo("Image History", 41491, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_HISTORY = tagInfo222;
        TagInfo tagInfo223 = new TagInfo("Subject Location", 41492, (FieldType) FIELD_TYPE_SHORT, 2, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_LOCATION_2 = tagInfo223;
        TagInfo tagInfo224 = new TagInfo("Exposure Index", 41493, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD = tagInfo224;
        TagInfo tagInfo225 = new TagInfo("TIFF- EPStandard ID", 41494, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TIFF_EPSTANDARD_ID_2 = tagInfo225;
        TagInfo tagInfo226 = new TagInfo("Sensing Method", 41495, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SENSING_METHOD_EXIF_IFD = tagInfo226;
        TagInfo tagInfo227 = new TagInfo("File Source", 41728, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FILE_SOURCE = tagInfo227;
        TagInfo tagInfo228 = new TagInfo("Scene Type", 41729, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_TYPE = tagInfo228;
        TagInfo tagInfo229 = new TagInfo("CFAPattern", 41730, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CFAPATTERN = tagInfo229;
        TagInfo tagInfo230 = new TagInfo("Custom Rendered", 41985, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CUSTOM_RENDERED = tagInfo230;
        TagInfo tagInfo231 = new TagInfo("Exposure Mode", 41986, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_MODE = tagInfo231;
        TagInfo tagInfo232 = new TagInfo("White Balance", 41987, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_1 = tagInfo232;
        TagInfo tagInfo233 = new TagInfo("Digital Zoom Ratio", 41988, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DIGITAL_ZOOM_RATIO = tagInfo233;
        TagInfo tagInfo234 = new TagInfo("Focal Length In 3 5mm Format", 41989, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT = tagInfo234;
        TagInfo tagInfo235 = new TagInfo("Scene Capture Type", 41990, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_CAPTURE_TYPE = tagInfo235;
        TagInfo tagInfo236 = new TagInfo("Gain Control", 41991, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAIN_CONTROL = tagInfo236;
        TagInfo tagInfo237 = new TagInfo("Contrast", 41992, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_1 = tagInfo237;
        TagInfo tagInfo238 = new TagInfo("Saturation", 41993, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_1 = tagInfo238;
        TagInfo tagInfo239 = new TagInfo("Sharpness", 41994, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_1 = tagInfo239;
        TagInfo tagInfo240 = new TagInfo("Device Setting Description", 41995, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DEVICE_SETTING_DESCRIPTION = tagInfo240;
        TagInfo tagInfo241 = new TagInfo("Subject Distance Range", 41996, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_DISTANCE_RANGE = tagInfo241;
        TagInfo tagInfo242 = new TagInfo("Image Unique ID", 42016, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_UNIQUE_ID = tagInfo242;
        TagInfo tagInfo243 = new TagInfo("GDALMetadata", 42112, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GDALMETADATA = tagInfo243;
        TagInfo tagInfo244 = new TagInfo("GDALNo Data", 42113, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_GDALNO_DATA = tagInfo244;
        TagInfo tagInfo245 = new TagInfo("Gamma", 42240, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAMMA = tagInfo245;
        TagInfo tagInfo246 = new TagInfo("Pixel Format", 48129, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_FORMAT = tagInfo246;
        TagInfo tagInfo247 = new TagInfo("Transfomation", 48130, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSFOMATION = tagInfo247;
        TagInfo tagInfo248 = new TagInfo("Uncompressed", 48131, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_UNCOMPRESSED = tagInfo248;
        TagInfo tagInfo249 = new TagInfo("Image Type", 48132, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_TYPE = tagInfo249;
        TagInfo tagInfo250 = new TagInfo("Image Width", 48256, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_WIDTH = tagInfo250;
        TagInfo tagInfo251 = new TagInfo("Image Height", 48257, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_HEIGHT = tagInfo251;
        TagInfo tagInfo252 = new TagInfo("Width Resolution", 48258, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_WIDTH_RESOLUTION = tagInfo252;
        TagInfo tagInfo253 = new TagInfo("Height Resolution", 48259, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_HEIGHT_RESOLUTION = tagInfo253;
        TagInfo tagInfo254 = new TagInfo("Image Offset", 48320, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_OFFSET = tagInfo254;
        TagInfo tagInfo255 = new TagInfo("Image Byte Count", 48321, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_BYTE_COUNT = tagInfo255;
        TagInfo tagInfo256 = new TagInfo("Alpha Offset", 48322, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_OFFSET = tagInfo256;
        TagInfo tagInfo257 = new TagInfo("Alpha Byte Count", 48323, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_BYTE_COUNT = tagInfo257;
        TagInfo tagInfo258 = new TagInfo("Image Data Discard", 48324, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_DATA_DISCARD = tagInfo258;
        TagInfo tagInfo259 = new TagInfo("Alpha Data Discard", 48325, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALPHA_DATA_DISCARD = tagInfo259;
        TagInfo tagInfo260 = new TagInfo("Oce Scanjob Desc", 50215, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OCE_SCANJOB_DESC = tagInfo260;
        TagInfo tagInfo261 = new TagInfo("Oce Application Selector", 50216, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OCE_APPLICATION_SELECTOR = tagInfo261;
        TagInfo tagInfo262 = new TagInfo("Oce IDNumber", 50217, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OCE_IDNUMBER = tagInfo262;
        TagInfo tagInfo263 = new TagInfo("Oce Image Logic", 50218, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_OCE_IMAGE_LOGIC = tagInfo263;
        TagInfo tagInfo264 = new TagInfo("Annotations", 50255, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ANNOTATIONS = tagInfo264;
        TagInfo tagInfo265 = new TagInfo("Print IM", 50341, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PRINT_IM = tagInfo265;
        TagInfo tagInfo266 = new TagInfo("DNG Version", 50706, (FieldType) FIELD_TYPE_BYTE, 4, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_VERSION = tagInfo266;
        TagInfo tagInfo267 = new TagInfo("DNG Backward Version", 50707, (FieldType) FIELD_TYPE_BYTE, 4, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_BACKWARD_VERSION = tagInfo267;
        TagInfo tagInfo268 = new TagInfo("Unique Camera Model", 50708, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_UNIQUE_CAMERA_MODEL = tagInfo268;
        TagInfo tagInfo269 = new TagInfo("Localized Camera Model", 50709, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_LOCALIZED_CAMERA_MODEL = tagInfo269;
        TagInfo tagInfo270 = new TagInfo("CFAPlane Color", 50710, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CFAPLANE_COLOR = tagInfo270;
        TagInfo tagInfo271 = new TagInfo("CFALayout", 50711, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CFALAYOUT = tagInfo271;
        TagInfo tagInfo272 = new TagInfo("Linearization Table", 50712, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LINEARIZATION_TABLE = tagInfo272;
        TagInfo tagInfo273 = new TagInfo("Black Level Repeat Dim", 50713, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_REPEAT_DIM = tagInfo273;
        TagInfo tagInfo274 = new TagInfo("Black Level", 50714, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL = tagInfo274;
        TagInfo tagInfo275 = new TagInfo("Black Level Delta H", 50715, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_DELTA_H = tagInfo275;
        TagInfo tagInfo276 = new TagInfo("Black Level Delta V", 50716, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BLACK_LEVEL_DELTA_V = tagInfo276;
        TagInfo tagInfo277 = new TagInfo("White Level", 50717, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_WHITE_LEVEL = tagInfo277;
        TagInfo tagInfo278 = new TagInfo("Default Scale", 50718, (FieldType) FIELD_TYPE_RATIONAL, 2, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_DEFAULT_SCALE = tagInfo278;
        TagInfo tagInfo279 = new TagInfo("Default Crop Origin", 50719, (FieldType) FIELD_TYPE_LONG, 2, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_DEFAULT_CROP_ORIGIN = tagInfo279;
        TagInfo tagInfo280 = new TagInfo("Default Crop Size", 50720, (FieldType) FIELD_TYPE_LONG, 2, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_DEFAULT_CROP_SIZE = tagInfo280;
        TagInfo tagInfo281 = new TagInfo("Color Matrix 1", 50721, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_MATRIX_1 = tagInfo281;
        TagInfo tagInfo282 = new TagInfo("Color Matrix 2", 50722, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_MATRIX_2 = tagInfo282;
        TagInfo tagInfo283 = new TagInfo("Camera Calibration 1", 50723, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CAMERA_CALIBRATION_1 = tagInfo283;
        TagInfo tagInfo284 = new TagInfo("Camera Calibration 2", 50724, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CAMERA_CALIBRATION_2 = tagInfo284;
        TagInfo tagInfo285 = new TagInfo("Reduction Matrix 1", 50725, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_REDUCTION_MATRIX_1 = tagInfo285;
        TagInfo tagInfo286 = new TagInfo("Reduction Matrix 2", 50726, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_REDUCTION_MATRIX_2 = tagInfo286;
        TagInfo tagInfo287 = new TagInfo("Analog Balance", 50727, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ANALOG_BALANCE = tagInfo287;
        TagInfo tagInfo288 = new TagInfo("As Shot Neutral", 50728, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AS_SHOT_NEUTRAL = tagInfo288;
        TagInfo tagInfo289 = new TagInfo("As Shot White XY", 50729, (FieldType) FIELD_TYPE_RATIONAL, 2, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_AS_SHOT_WHITE_XY = tagInfo289;
        TagInfo tagInfo290 = new TagInfo("Baseline Exposure", 50730, FIELD_TYPE_SRATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_EXPOSURE = tagInfo290;
        TagInfo tagInfo291 = new TagInfo("Baseline Noise", 50731, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_NOISE = tagInfo291;
        TagInfo tagInfo292 = new TagInfo("Baseline Sharpness", 50732, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_BASELINE_SHARPNESS = tagInfo292;
        TagInfo tagInfo293 = new TagInfo("Bayer Green Split", 50733, (FieldType) FIELD_TYPE_LONG, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_BAYER_GREEN_SPLIT = tagInfo293;
        TagInfo tagInfo294 = new TagInfo("Linear Response Limit", 50734, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_LINEAR_RESPONSE_LIMIT = tagInfo294;
        TagInfo tagInfo295 = new TagInfo("Camera Serial Number", 50735, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CAMERA_SERIAL_NUMBER = tagInfo295;
        TagInfo tagInfo296 = new TagInfo("DNG Lens Info", 50736, (FieldType) FIELD_TYPE_RATIONAL, 4, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_DNG_LENS_INFO = tagInfo296;
        TagInfo tagInfo297 = new TagInfo("Chroma Blur Radius", 50737, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_CHROMA_BLUR_RADIUS = tagInfo297;
        TagInfo tagInfo298 = new TagInfo("Anti Alias Strength", 50738, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_ANTI_ALIAS_STRENGTH = tagInfo298;
        TagInfo tagInfo299 = new TagInfo("Shadow Scale", 50739, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SHADOW_SCALE = tagInfo299;
        TagInfo tagInfo300 = new TagInfo("DNG Adobe Data", 50740, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DNG_ADOBE_DATA = tagInfo300;
        TagInfo tagInfo301 = new TagInfo("DNG Pentax Data", 50740, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DNG_PENTAX_DATA = tagInfo301;
        TagInfo tagInfo302 = new TagInfo("DNG Private Data", 50740, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DNG_PRIVATE_DATA = tagInfo302;
        TagInfo tagInfo303 = new TagInfo("Maker Note Safety", 50741, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_MAKER_NOTE_SAFETY = tagInfo303;
        TagInfo tagInfo304 = new TagInfo("Calibration Illuminant 1", 50778, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CALIBRATION_ILLUMINANT_1 = tagInfo304;
        TagInfo tagInfo305 = new TagInfo("Calibration Illuminant 2", 50779, (FieldType) FIELD_TYPE_SHORT, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_CALIBRATION_ILLUMINANT_2 = tagInfo305;
        TagInfo tagInfo306 = new TagInfo("Best Quality Scale", 50780, (FieldType) FIELD_TYPE_RATIONAL, 1, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_BEST_QUALITY_SCALE = tagInfo306;
        TagInfo tagInfo307 = new TagInfo("Raw Data Unique ID", 50781, (FieldType) FIELD_TYPE_BYTE, 16, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_RAW_DATA_UNIQUE_ID = tagInfo307;
        TagInfo tagInfo308 = new TagInfo("Alias Layer Metadata", 50784, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ALIAS_LAYER_METADATA = tagInfo308;
        TagInfo tagInfo309 = new TagInfo("Original Raw File Name", 50827, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIGINAL_RAW_FILE_NAME = tagInfo309;
        TagInfo tagInfo310 = new TagInfo("Original Raw File Data", 50828, FIELD_TYPE_UNDEFINED, 1, EXIF_DIRECTORY_IFD0);
        EXIF_TAG_ORIGINAL_RAW_FILE_DATA = tagInfo310;
        TagInfo tagInfo311 = new TagInfo("Active Area", 50829, (FieldType) FIELD_TYPE_LONG, 4, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_ACTIVE_AREA = tagInfo311;
        TagInfo tagInfo312 = new TagInfo("Masked Areas", 50830, (FieldType) FIELD_TYPE_LONG, 4, EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_MASKED_AREAS = tagInfo312;
        TagInfo tagInfo313 = new TagInfo("As Shot ICCProfile", 50831, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AS_SHOT_ICCPROFILE = tagInfo313;
        TagInfo tagInfo314 = new TagInfo("As Shot Pre Profile Matrix", 50832, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX = tagInfo314;
        TagInfo tagInfo315 = new TagInfo("Current ICCProfile", 50833, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CURRENT_ICCPROFILE = tagInfo315;
        TagInfo tagInfo316 = new TagInfo("Current Pre Profile Matrix", 50834, FIELD_TYPE_DESCRIPTION_UNKNOWN, 1, EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX = tagInfo316;
        TagInfo tagInfo317 = new TagInfo("Offset Schema", 59933, FIELD_TYPE_SLONG, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OFFSET_SCHEMA = tagInfo317;
        TagInfo tagInfo318 = new TagInfo("Owner Name", 65000, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OWNER_NAME = tagInfo318;
        TagInfo tagInfo319 = new TagInfo("Serial Number", 65001, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SERIAL_NUMBER = tagInfo319;
        TagInfo tagInfo320 = new TagInfo("Lens", 65002, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS = tagInfo320;
        TagInfo tagInfo321 = new TagInfo("Raw File", 65100, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RAW_FILE = tagInfo321;
        TagInfo tagInfo322 = new TagInfo("Converter", 65101, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONVERTER = tagInfo322;
        TagInfo tagInfo323 = new TagInfo("White Balance", 65102, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_2 = tagInfo323;
        TagInfo tagInfo324 = new TagInfo("Exposure", 65105, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE = tagInfo324;
        TagInfo tagInfo325 = new TagInfo("Shadows", 65106, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHADOWS = tagInfo325;
        TagInfo tagInfo326 = new TagInfo("Brightness", 65107, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS = tagInfo326;
        TagInfo tagInfo327 = new TagInfo("Contrast", 65108, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_2 = tagInfo327;
        TagInfo tagInfo328 = new TagInfo("Saturation", 65109, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_2 = tagInfo328;
        TagInfo tagInfo329 = new TagInfo("Sharpness", 65110, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_2 = tagInfo329;
        TagInfo tagInfo330 = new TagInfo("Smoothness", 65111, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SMOOTHNESS = tagInfo330;
        TagInfo tagInfo331 = new TagInfo("Moire Filter", 65112, (FieldType) FIELD_TYPE_ASCII, 1, EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MOIRE_FILTER = tagInfo331;
        TagInfo[] tagInfoArr = new TagInfo[FacebookRequestErrorClassification.EC_TOO_MANY_USER_ACTION_CALLS];
        tagInfoArr[0] = EXIF_TAG_INTEROP_INDEX;
        tagInfoArr[1] = EXIF_TAG_INTEROP_VERSION;
        tagInfoArr[2] = EXIF_TAG_PROCESSING_SOFTWARE;
        tagInfoArr[3] = EXIF_TAG_SUBFILE_TYPE;
        tagInfoArr[4] = EXIF_TAG_OLD_SUBFILE_TYPE;
        tagInfoArr[5] = EXIF_TAG_IMAGE_WIDTH_IFD0;
        tagInfoArr[6] = EXIF_TAG_IMAGE_HEIGHT_IFD0;
        tagInfoArr[7] = EXIF_TAG_BITS_PER_SAMPLE;
        tagInfoArr[8] = EXIF_TAG_COMPRESSION;
        tagInfoArr[9] = EXIF_TAG_PHOTOMETRIC_INTERPRETATION;
        tagInfoArr[10] = EXIF_TAG_THRESHOLDING;
        tagInfoArr[11] = EXIF_TAG_CELL_WIDTH;
        tagInfoArr[12] = EXIF_TAG_CELL_LENGTH;
        tagInfoArr[13] = EXIF_TAG_FILL_ORDER;
        tagInfoArr[14] = EXIF_TAG_DOCUMENT_NAME;
        tagInfoArr[15] = EXIF_TAG_IMAGE_DESCRIPTION;
        tagInfoArr[16] = EXIF_TAG_MAKE;
        tagInfoArr[17] = EXIF_TAG_MODEL;
        tagInfoArr[18] = EXIF_TAG_PREVIEW_IMAGE_START_IFD0;
        tagInfoArr[19] = EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1;
        tagInfoArr[20] = EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2;
        tagInfoArr[21] = EXIF_TAG_ORIENTATION;
        tagInfoArr[22] = EXIF_TAG_SAMPLES_PER_PIXEL;
        tagInfoArr[23] = EXIF_TAG_ROWS_PER_STRIP;
        tagInfoArr[24] = EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0;
        tagInfoArr[25] = EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1;
        tagInfoArr[26] = EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2;
        tagInfoArr[27] = EXIF_TAG_MIN_SAMPLE_VALUE;
        tagInfoArr[28] = EXIF_TAG_MAX_SAMPLE_VALUE;
        tagInfoArr[29] = EXIF_TAG_XRESOLUTION;
        tagInfoArr[30] = EXIF_TAG_YRESOLUTION;
        tagInfoArr[31] = EXIF_TAG_PLANAR_CONFIGURATION;
        tagInfoArr[32] = EXIF_TAG_PAGE_NAME;
        tagInfoArr[33] = EXIF_TAG_XPOSITION;
        tagInfoArr[34] = EXIF_TAG_YPOSITION;
        tagInfoArr[35] = EXIF_TAG_FREE_OFFSETS;
        tagInfoArr[36] = EXIF_TAG_FREE_BYTE_COUNTS;
        tagInfoArr[37] = EXIF_TAG_GRAY_RESPONSE_UNIT;
        tagInfoArr[38] = EXIF_TAG_GRAY_RESPONSE_CURVE;
        tagInfoArr[39] = EXIF_TAG_T4OPTIONS;
        tagInfoArr[40] = EXIF_TAG_T6OPTIONS;
        tagInfoArr[41] = EXIF_TAG_RESOLUTION_UNIT;
        tagInfoArr[42] = EXIF_TAG_PAGE_NUMBER;
        tagInfoArr[43] = EXIF_TAG_COLOR_RESPONSE_UNIT;
        tagInfoArr[44] = EXIF_TAG_TRANSFER_FUNCTION;
        tagInfoArr[45] = EXIF_TAG_SOFTWARE;
        tagInfoArr[46] = EXIF_TAG_MODIFY_DATE;
        tagInfoArr[47] = EXIF_TAG_ARTIST;
        tagInfoArr[48] = EXIF_TAG_HOST_COMPUTER;
        tagInfoArr[49] = EXIF_TAG_PREDICTOR;
        tagInfoArr[50] = EXIF_TAG_WHITE_POINT;
        tagInfoArr[51] = EXIF_TAG_PRIMARY_CHROMATICITIES;
        tagInfoArr[52] = EXIF_TAG_COLOR_MAP;
        tagInfoArr[53] = EXIF_TAG_HALFTONE_HINTS;
        tagInfoArr[54] = EXIF_TAG_TILE_WIDTH;
        tagInfoArr[55] = EXIF_TAG_TILE_LENGTH;
        tagInfoArr[56] = EXIF_TAG_TILE_OFFSETS;
        tagInfoArr[57] = EXIF_TAG_TILE_BYTE_COUNTS;
        tagInfoArr[58] = EXIF_TAG_BAD_FAX_LINES;
        tagInfoArr[59] = EXIF_TAG_CLEAN_FAX_DATA;
        tagInfoArr[60] = EXIF_TAG_CONSECUTIVE_BAD_FAX_LINES;
        tagInfoArr[61] = EXIF_TAG_SUB_IFD;
        tagInfoArr[62] = EXIF_TAG_INK_SET;
        tagInfoArr[63] = EXIF_TAG_INK_NAMES;
        tagInfoArr[64] = EXIF_TAG_NUMBEROF_INKS;
        tagInfoArr[65] = EXIF_TAG_DOT_RANGE;
        tagInfoArr[66] = EXIF_TAG_TARGET_PRINTER;
        tagInfoArr[67] = EXIF_TAG_EXTRA_SAMPLES;
        tagInfoArr[68] = EXIF_TAG_SAMPLE_FORMAT;
        tagInfoArr[69] = EXIF_TAG_SMIN_SAMPLE_VALUE;
        tagInfoArr[70] = EXIF_TAG_SMAX_SAMPLE_VALUE;
        tagInfoArr[71] = EXIF_TAG_TRANSFER_RANGE;
        tagInfoArr[72] = EXIF_TAG_CLIP_PATH;
        tagInfoArr[73] = EXIF_TAG_XCLIP_PATH_UNITS;
        tagInfoArr[74] = EXIF_TAG_YCLIP_PATH_UNITS;
        tagInfoArr[75] = EXIF_TAG_INDEXED;
        tagInfoArr[76] = EXIF_TAG_JPEGTABLES;
        tagInfoArr[77] = EXIF_TAG_OPIPROXY;
        tagInfoArr[78] = EXIF_TAG_GLOBAL_PARAMETERS_IFD;
        tagInfoArr[79] = EXIF_TAG_PROFILE_TYPE;
        tagInfoArr[80] = EXIF_TAG_FAX_PROFILE;
        tagInfoArr[81] = EXIF_TAG_CODING_METHODS;
        tagInfoArr[82] = EXIF_TAG_VERSION_YEAR;
        tagInfoArr[83] = EXIF_TAG_MODE_NUMBER;
        tagInfoArr[84] = EXIF_TAG_DECODE;
        tagInfoArr[85] = EXIF_TAG_DEFAULT_IMAGE_COLOR;
        tagInfoArr[86] = EXIF_TAG_JPEGPROC;
        tagInfoArr[87] = EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES;
        tagInfoArr[88] = EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD;
        tagInfoArr[89] = EXIF_TAG_JPG_FROM_RAW_START_IFD2;
        tagInfoArr[90] = EXIF_TAG_OTHER_IMAGE_START;
        tagInfoArr[91] = EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES;
        tagInfoArr[92] = EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD;
        tagInfoArr[93] = EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2;
        tagInfoArr[94] = EXIF_TAG_OTHER_IMAGE_LENGTH;
        tagInfoArr[95] = EXIF_TAG_JPEGRESTART_INTERVAL;
        tagInfoArr[96] = EXIF_TAG_JPEGLOSSLESS_PREDICTORS;
        tagInfoArr[97] = EXIF_TAG_JPEGPOINT_TRANSFORMS;
        tagInfoArr[98] = EXIF_TAG_JPEGQTABLES;
        tagInfoArr[99] = EXIF_TAG_JPEGDCTABLES;
        tagInfoArr[100] = EXIF_TAG_JPEGACTABLES;
        tagInfoArr[101] = EXIF_TAG_YCBCR_COEFFICIENTS;
        tagInfoArr[102] = EXIF_TAG_YCBCR_SUB_SAMPLING;
        tagInfoArr[103] = EXIF_TAG_YCBCR_POSITIONING;
        tagInfoArr[104] = EXIF_TAG_REFERENCE_BLACK_WHITE;
        tagInfoArr[105] = EXIF_TAG_STRIP_ROW_COUNTS;
        tagInfoArr[106] = EXIF_TAG_APPLICATION_NOTES;
        tagInfoArr[107] = EXIF_TAG_RELATED_IMAGE_FILE_FORMAT;
        tagInfoArr[108] = EXIF_TAG_RELATED_IMAGE_WIDTH;
        tagInfoArr[109] = EXIF_TAG_RELATED_IMAGE_LENGTH;
        tagInfoArr[110] = EXIF_TAG_RATING;
        tagInfoArr[111] = EXIF_TAG_RATING_PERCENT;
        tagInfoArr[112] = EXIF_TAG_IMAGE_ID;
        tagInfoArr[113] = EXIF_TAG_WANG_ANNOTATION;
        tagInfoArr[114] = EXIF_TAG_MATTEING;
        tagInfoArr[115] = EXIF_TAG_DATA_TYPE;
        tagInfoArr[116] = EXIF_TAG_IMAGE_DEPTH;
        tagInfoArr[117] = EXIF_TAG_TILE_DEPTH;
        tagInfoArr[118] = EXIF_TAG_MODEL_2;
        tagInfoArr[119] = EXIF_TAG_CFAREPEAT_PATTERN_DIM;
        tagInfoArr[120] = EXIF_TAG_CFAPATTERN_2;
        tagInfoArr[121] = EXIF_TAG_BATTERY_LEVEL;
        tagInfoArr[122] = EXIF_TAG_COPYRIGHT;
        tagInfoArr[123] = EXIF_TAG_EXPOSURE_TIME;
        tagInfoArr[124] = EXIF_TAG_FNUMBER;
        tagInfoArr[125] = EXIF_TAG_MDFILE_TAG;
        tagInfoArr[126] = EXIF_TAG_MDSCALE_PIXEL;
        tagInfoArr[127] = EXIF_TAG_MDCOLOR_TABLE;
        tagInfoArr[128] = EXIF_TAG_MDLAB_NAME;
        tagInfoArr[129] = EXIF_TAG_MDSAMPLE_INFO;
        tagInfoArr[130] = EXIF_TAG_MDPREP_DATE;
        tagInfoArr[131] = EXIF_TAG_MDPREP_TIME;
        tagInfoArr[132] = EXIF_TAG_MDFILE_UNITS;
        tagInfoArr[133] = EXIF_TAG_PIXEL_SCALE;
        tagInfoArr[134] = EXIF_TAG_IPTC_NAA;
        tagInfoArr[135] = EXIF_TAG_INTERGRAPH_PACKET_DATA;
        tagInfoArr[136] = EXIF_TAG_INTERGRAPH_FLAG_REGISTERS;
        tagInfoArr[137] = EXIF_TAG_INTERGRAPH_MATRIX;
        tagInfoArr[138] = EXIF_TAG_MODEL_TIE_POINT;
        tagInfoArr[139] = EXIF_TAG_SITE;
        tagInfoArr[140] = EXIF_TAG_COLOR_SEQUENCE;
        tagInfoArr[141] = EXIF_TAG_IT8HEADER;
        tagInfoArr[142] = EXIF_TAG_RASTER_PADDING;
        tagInfoArr[143] = EXIF_TAG_BITS_PER_RUN_LENGTH;
        tagInfoArr[144] = EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH;
        tagInfoArr[145] = EXIF_TAG_COLOR_TABLE;
        tagInfoArr[146] = EXIF_TAG_IMAGE_COLOR_INDICATOR;
        tagInfoArr[147] = EXIF_TAG_BACKGROUND_COLOR_INDICATOR;
        tagInfoArr[148] = EXIF_TAG_IMAGE_COLOR_VALUE;
        tagInfoArr[149] = EXIF_TAG_BACKGROUND_COLOR_VALUE;
        tagInfoArr[150] = EXIF_TAG_PIXEL_INTENSITY_RANGE;
        tagInfoArr[151] = EXIF_TAG_TRANSPARENCY_INDICATOR;
        tagInfoArr[152] = EXIF_TAG_COLOR_CHARACTERIZATION;
        tagInfoArr[153] = EXIF_TAG_HCUSAGE;
        tagInfoArr[154] = EXIF_TAG_SEMINFO;
        tagInfoArr[155] = EXIF_TAG_AFCP_IPTC;
        tagInfoArr[156] = EXIF_TAG_MODEL_TRANSFORM;
        tagInfoArr[157] = EXIF_TAG_LEAF_DATA;
        tagInfoArr[158] = EXIF_TAG_PHOTOSHOP_SETTINGS;
        tagInfoArr[159] = EXIF_TAG_EXIF_OFFSET;
        tagInfoArr[160] = EXIF_TAG_ICC_PROFILE;
        tagInfoArr[161] = EXIF_TAG_IMAGE_LAYER;
        tagInfoArr[162] = EXIF_TAG_GEO_TIFF_DIRECTORY;
        tagInfoArr[163] = EXIF_TAG_GEO_TIFF_DOUBLE_PARAMS;
        tagInfoArr[164] = EXIF_TAG_GEO_TIFF_ASCII_PARAMS;
        tagInfoArr[165] = EXIF_TAG_EXPOSURE_PROGRAM;
        tagInfoArr[166] = EXIF_TAG_SPECTRAL_SENSITIVITY;
        tagInfoArr[167] = EXIF_TAG_GPSINFO;
        tagInfoArr[168] = EXIF_TAG_ISO;
        tagInfoArr[169] = EXIF_TAG_OPTO__ELECTRIC_CONV_FACTOR;
        tagInfoArr[170] = EXIF_TAG_INTERLACE;
        tagInfoArr[171] = EXIF_TAG_TIME_ZONE_OFFSET;
        tagInfoArr[172] = EXIF_TAG_SELF_TIMER_MODE;
        tagInfoArr[173] = EXIF_TAG_FAX_RECV_PARAMS;
        tagInfoArr[174] = EXIF_TAG_FAX_SUB_ADDRESS;
        tagInfoArr[175] = EXIF_TAG_FAX_RECV_TIME;
        tagInfoArr[176] = EXIF_TAG_LEAF_SUB_IFD;
        tagInfoArr[177] = EXIF_TAG_EXIF_VERSION;
        tagInfoArr[178] = EXIF_TAG_DATE_TIME_ORIGINAL;
        tagInfoArr[179] = EXIF_TAG_CREATE_DATE;
        tagInfoArr[180] = EXIF_TAG_COMPONENTS_CONFIGURATION;
        tagInfoArr[181] = EXIF_TAG_COMPRESSED_BITS_PER_PIXEL;
        tagInfoArr[182] = EXIF_TAG_SHUTTER_SPEED_VALUE;
        tagInfoArr[183] = EXIF_TAG_APERTURE_VALUE;
        tagInfoArr[184] = EXIF_TAG_BRIGHTNESS_VALUE;
        tagInfoArr[185] = EXIF_TAG_EXPOSURE_COMPENSATION;
        tagInfoArr[186] = EXIF_TAG_MAX_APERTURE_VALUE;
        tagInfoArr[187] = EXIF_TAG_SUBJECT_DISTANCE;
        tagInfoArr[188] = EXIF_TAG_METERING_MODE;
        tagInfoArr[189] = EXIF_TAG_LIGHT_SOURCE;
        tagInfoArr[190] = EXIF_TAG_FLASH;
        tagInfoArr[191] = EXIF_TAG_FOCAL_LENGTH;
        tagInfoArr[192] = EXIF_TAG_FLASH_ENERGY;
        tagInfoArr[193] = EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_1;
        tagInfoArr[194] = EXIF_TAG_NOISE_1;
        tagInfoArr[195] = EXIF_TAG_FOCAL_PLANE_XRESOLUTION;
        tagInfoArr[196] = EXIF_TAG_FOCAL_PLANE_YRESOLUTION;
        tagInfoArr[197] = EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT;
        tagInfoArr[198] = EXIF_TAG_IMAGE_NUMBER_EXIF_IFD;
        tagInfoArr[199] = EXIF_TAG_SECURITY_CLASSIFICATION_EXIF_IFD;
        tagInfoArr[200] = EXIF_TAG_IMAGE_HISTORY_EXIF_IFD;
        tagInfoArr[201] = EXIF_TAG_SUBJECT_LOCATION_1;
        tagInfoArr[202] = EXIF_TAG_EXPOSURE_INDEX;
        tagInfoArr[203] = EXIF_TAG_TIFF_EPSTANDARD_ID_1;
        tagInfoArr[204] = EXIF_TAG_SENSING_METHOD;
        tagInfoArr[205] = EXIF_TAG_STO_NITS;
        tagInfoArr[206] = EXIF_TAG_SUB_SEC_TIME;
        tagInfoArr[207] = EXIF_TAG_SUB_SEC_TIME_ORIGINAL;
        tagInfoArr[208] = EXIF_TAG_SUB_SEC_TIME_DIGITIZED;
        tagInfoArr[209] = EXIF_TAG_IMAGE_SOURCE_DATA;
        tagInfoArr[210] = EXIF_TAG_XPTITLE;
        tagInfoArr[211] = EXIF_TAG_XPCOMMENT;
        tagInfoArr[212] = EXIF_TAG_XPAUTHOR;
        tagInfoArr[213] = EXIF_TAG_XPKEYWORDS;
        tagInfoArr[214] = EXIF_TAG_XPSUBJECT;
        tagInfoArr[215] = EXIF_TAG_FLASHPIX_VERSION;
        tagInfoArr[216] = EXIF_TAG_COLOR_SPACE;
        tagInfoArr[217] = EXIF_TAG_EXIF_IMAGE_WIDTH;
        tagInfoArr[218] = EXIF_TAG_EXIF_IMAGE_LENGTH;
        tagInfoArr[219] = EXIF_TAG_RELATED_SOUND_FILE;
        tagInfoArr[220] = EXIF_TAG_INTEROP_OFFSET;
        tagInfoArr[221] = EXIF_TAG_FLASH_ENERGY_EXIF_IFD;
        tagInfoArr[222] = EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2;
        tagInfoArr[223] = EXIF_TAG_NOISE_2;
        tagInfoArr[224] = EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD;
        tagInfoArr[225] = EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD;
        tagInfoArr[226] = EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD;
        tagInfoArr[227] = EXIF_TAG_IMAGE_NUMBER;
        tagInfoArr[228] = EXIF_TAG_SECURITY_CLASSIFICATION;
        tagInfoArr[229] = EXIF_TAG_IMAGE_HISTORY;
        tagInfoArr[230] = EXIF_TAG_SUBJECT_LOCATION_2;
        tagInfoArr[231] = EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD;
        tagInfoArr[232] = EXIF_TAG_TIFF_EPSTANDARD_ID_2;
        tagInfoArr[233] = EXIF_TAG_SENSING_METHOD_EXIF_IFD;
        tagInfoArr[234] = EXIF_TAG_FILE_SOURCE;
        tagInfoArr[235] = EXIF_TAG_SCENE_TYPE;
        tagInfoArr[236] = EXIF_TAG_CFAPATTERN;
        tagInfoArr[237] = EXIF_TAG_CUSTOM_RENDERED;
        tagInfoArr[238] = EXIF_TAG_EXPOSURE_MODE;
        tagInfoArr[239] = EXIF_TAG_WHITE_BALANCE_1;
        tagInfoArr[240] = EXIF_TAG_DIGITAL_ZOOM_RATIO;
        tagInfoArr[241] = EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT;
        tagInfoArr[242] = EXIF_TAG_SCENE_CAPTURE_TYPE;
        tagInfoArr[243] = EXIF_TAG_GAIN_CONTROL;
        tagInfoArr[244] = EXIF_TAG_CONTRAST_1;
        tagInfoArr[245] = EXIF_TAG_SATURATION_1;
        tagInfoArr[246] = EXIF_TAG_SHARPNESS_1;
        tagInfoArr[247] = EXIF_TAG_DEVICE_SETTING_DESCRIPTION;
        tagInfoArr[248] = EXIF_TAG_SUBJECT_DISTANCE_RANGE;
        tagInfoArr[249] = EXIF_TAG_IMAGE_UNIQUE_ID;
        tagInfoArr[250] = EXIF_TAG_GDALMETADATA;
        tagInfoArr[251] = EXIF_TAG_GDALNO_DATA;
        tagInfoArr[252] = EXIF_TAG_GAMMA;
        tagInfoArr[253] = EXIF_TAG_PIXEL_FORMAT;
        tagInfoArr[254] = EXIF_TAG_TRANSFOMATION;
        tagInfoArr[255] = EXIF_TAG_UNCOMPRESSED;
        tagInfoArr[256] = EXIF_TAG_IMAGE_TYPE;
        tagInfoArr[257] = EXIF_TAG_IMAGE_WIDTH;
        tagInfoArr[258] = EXIF_TAG_IMAGE_HEIGHT;
        tagInfoArr[259] = EXIF_TAG_WIDTH_RESOLUTION;
        tagInfoArr[260] = EXIF_TAG_HEIGHT_RESOLUTION;
        tagInfoArr[261] = EXIF_TAG_IMAGE_OFFSET;
        tagInfoArr[262] = EXIF_TAG_IMAGE_BYTE_COUNT;
        tagInfoArr[263] = EXIF_TAG_ALPHA_OFFSET;
        tagInfoArr[264] = EXIF_TAG_ALPHA_BYTE_COUNT;
        tagInfoArr[265] = EXIF_TAG_IMAGE_DATA_DISCARD;
        tagInfoArr[266] = EXIF_TAG_ALPHA_DATA_DISCARD;
        tagInfoArr[267] = EXIF_TAG_OCE_SCANJOB_DESC;
        tagInfoArr[268] = EXIF_TAG_OCE_APPLICATION_SELECTOR;
        tagInfoArr[269] = EXIF_TAG_OCE_IDNUMBER;
        tagInfoArr[270] = EXIF_TAG_OCE_IMAGE_LOGIC;
        tagInfoArr[271] = EXIF_TAG_ANNOTATIONS;
        tagInfoArr[272] = EXIF_TAG_PRINT_IM;
        tagInfoArr[273] = EXIF_TAG_DNG_VERSION;
        tagInfoArr[274] = EXIF_TAG_DNG_BACKWARD_VERSION;
        tagInfoArr[275] = EXIF_TAG_UNIQUE_CAMERA_MODEL;
        tagInfoArr[276] = EXIF_TAG_LOCALIZED_CAMERA_MODEL;
        tagInfoArr[277] = EXIF_TAG_CFAPLANE_COLOR;
        tagInfoArr[278] = EXIF_TAG_CFALAYOUT;
        tagInfoArr[279] = EXIF_TAG_LINEARIZATION_TABLE;
        tagInfoArr[280] = EXIF_TAG_BLACK_LEVEL_REPEAT_DIM;
        tagInfoArr[281] = EXIF_TAG_BLACK_LEVEL;
        tagInfoArr[282] = EXIF_TAG_BLACK_LEVEL_DELTA_H;
        tagInfoArr[283] = EXIF_TAG_BLACK_LEVEL_DELTA_V;
        tagInfoArr[284] = EXIF_TAG_WHITE_LEVEL;
        tagInfoArr[285] = EXIF_TAG_DEFAULT_SCALE;
        tagInfoArr[286] = EXIF_TAG_DEFAULT_CROP_ORIGIN;
        tagInfoArr[287] = EXIF_TAG_DEFAULT_CROP_SIZE;
        tagInfoArr[288] = EXIF_TAG_COLOR_MATRIX_1;
        tagInfoArr[289] = EXIF_TAG_COLOR_MATRIX_2;
        tagInfoArr[290] = EXIF_TAG_CAMERA_CALIBRATION_1;
        tagInfoArr[291] = EXIF_TAG_CAMERA_CALIBRATION_2;
        tagInfoArr[292] = EXIF_TAG_REDUCTION_MATRIX_1;
        tagInfoArr[293] = EXIF_TAG_REDUCTION_MATRIX_2;
        tagInfoArr[294] = EXIF_TAG_ANALOG_BALANCE;
        tagInfoArr[295] = EXIF_TAG_AS_SHOT_NEUTRAL;
        tagInfoArr[296] = EXIF_TAG_AS_SHOT_WHITE_XY;
        tagInfoArr[297] = EXIF_TAG_BASELINE_EXPOSURE;
        tagInfoArr[298] = EXIF_TAG_BASELINE_NOISE;
        tagInfoArr[299] = EXIF_TAG_BASELINE_SHARPNESS;
        tagInfoArr[300] = EXIF_TAG_BAYER_GREEN_SPLIT;
        tagInfoArr[301] = EXIF_TAG_LINEAR_RESPONSE_LIMIT;
        tagInfoArr[302] = EXIF_TAG_CAMERA_SERIAL_NUMBER;
        tagInfoArr[303] = EXIF_TAG_DNG_LENS_INFO;
        tagInfoArr[304] = EXIF_TAG_CHROMA_BLUR_RADIUS;
        tagInfoArr[305] = EXIF_TAG_ANTI_ALIAS_STRENGTH;
        tagInfoArr[306] = EXIF_TAG_SHADOW_SCALE;
        tagInfoArr[307] = EXIF_TAG_DNG_ADOBE_DATA;
        tagInfoArr[308] = EXIF_TAG_DNG_PENTAX_DATA;
        tagInfoArr[309] = EXIF_TAG_DNG_PRIVATE_DATA;
        tagInfoArr[310] = EXIF_TAG_MAKER_NOTE_SAFETY;
        tagInfoArr[311] = EXIF_TAG_CALIBRATION_ILLUMINANT_1;
        tagInfoArr[312] = EXIF_TAG_CALIBRATION_ILLUMINANT_2;
        tagInfoArr[313] = EXIF_TAG_BEST_QUALITY_SCALE;
        tagInfoArr[314] = EXIF_TAG_RAW_DATA_UNIQUE_ID;
        tagInfoArr[315] = EXIF_TAG_ALIAS_LAYER_METADATA;
        tagInfoArr[316] = EXIF_TAG_ORIGINAL_RAW_FILE_NAME;
        tagInfoArr[317] = EXIF_TAG_ORIGINAL_RAW_FILE_DATA;
        tagInfoArr[318] = EXIF_TAG_ACTIVE_AREA;
        tagInfoArr[319] = EXIF_TAG_MASKED_AREAS;
        tagInfoArr[320] = EXIF_TAG_AS_SHOT_ICCPROFILE;
        tagInfoArr[321] = EXIF_TAG_AS_SHOT_PRE_PROFILE_MATRIX;
        tagInfoArr[322] = EXIF_TAG_CURRENT_ICCPROFILE;
        tagInfoArr[323] = EXIF_TAG_CURRENT_PRE_PROFILE_MATRIX;
        tagInfoArr[324] = EXIF_TAG_OFFSET_SCHEMA;
        tagInfoArr[325] = EXIF_TAG_OWNER_NAME;
        tagInfoArr[326] = EXIF_TAG_SERIAL_NUMBER;
        tagInfoArr[327] = EXIF_TAG_LENS;
        tagInfoArr[328] = EXIF_TAG_RAW_FILE;
        tagInfoArr[329] = EXIF_TAG_CONVERTER;
        tagInfoArr[330] = EXIF_TAG_WHITE_BALANCE_2;
        tagInfoArr[331] = EXIF_TAG_EXPOSURE;
        tagInfoArr[332] = EXIF_TAG_SHADOWS;
        tagInfoArr[333] = EXIF_TAG_BRIGHTNESS;
        tagInfoArr[334] = EXIF_TAG_CONTRAST_2;
        tagInfoArr[335] = EXIF_TAG_SATURATION_2;
        tagInfoArr[336] = EXIF_TAG_SHARPNESS_2;
        tagInfoArr[337] = EXIF_TAG_SMOOTHNESS;
        tagInfoArr[338] = EXIF_TAG_MOIRE_FILTER;
        tagInfoArr[339] = EXIF_TAG_USER_COMMENT;
        tagInfoArr[340] = EXIF_TAG_MAKER_NOTE;
        ALL_EXIF_TAGS = tagInfoArr;
    }
}
