package io.requery.android.sqlitex;

import android.database.Cursor;
import android.database.sqlite.SQLiteException;
import io.requery.android.database.sqlite.SQLiteStatement;
import io.requery.android.sqlite.BasePreparedStatement;
import io.requery.android.sqlite.CursorResultSet;
import io.requery.android.sqlite.SingleResultSet;
import java.sql.ResultSet;
import java.sql.SQLException;

class SqlitexPreparedStatement extends BasePreparedStatement {
    private final SqlitexConnection connection;
    private Cursor cursor;
    private final SQLiteStatement statement;

    SqlitexPreparedStatement(SqlitexConnection sqlitexConnection, String str, int i) throws SQLException {
        super(sqlitexConnection, str, i);
        this.connection = sqlitexConnection;
        this.statement = sqlitexConnection.getDatabase().compileStatement(str);
    }

    /* access modifiers changed from: protected */
    public void bindNullOrString(int i, Object obj) {
        if (obj == null) {
            this.statement.bindNull(i);
            if (this.bindings != null) {
                this.bindings.add(null);
                return;
            }
            return;
        }
        String obj2 = obj.toString();
        this.statement.bindString(i, obj2);
        if (this.bindings != null) {
            this.bindings.add(obj2);
        }
    }

    /* access modifiers changed from: protected */
    public void bindLong(int i, long j) {
        this.statement.bindLong(i, j);
        if (this.bindings != null) {
            this.bindings.add(Long.valueOf(j));
        }
    }

    /* access modifiers changed from: protected */
    public void bindDouble(int i, double d) {
        this.statement.bindDouble(i, d);
        if (this.bindings != null) {
            this.bindings.add(Double.valueOf(d));
        }
    }

    /* access modifiers changed from: protected */
    public void bindBlob(int i, byte[] bArr) {
        if (bArr == null) {
            this.statement.bindNull(i);
            if (this.bindings != null) {
                this.bindings.add(null);
                return;
            }
            return;
        }
        this.statement.bindBlob(i, bArr);
        if (this.bindings != null) {
            bindBlobLiteral(i, bArr);
        }
    }

    public void close() throws SQLException {
        clearParameters();
        this.statement.close();
        Cursor cursor2 = this.cursor;
        if (cursor2 != null) {
            cursor2.close();
        }
        super.close();
    }

    public boolean execute(String str, int i) throws SQLException {
        throw new UnsupportedOperationException();
    }

    public ResultSet executeQuery(String str) throws SQLException {
        throw new UnsupportedOperationException();
    }

    public int executeUpdate(String str, int i) throws SQLException {
        throw new UnsupportedOperationException();
    }

    public void clearParameters() throws SQLException {
        this.statement.clearBindings();
        if (this.bindings != null) {
            this.bindings.clear();
        }
    }

    public boolean execute() throws SQLException {
        try {
            this.statement.execute();
        } catch (SQLiteException e) {
            SqlitexConnection.throwSQLException(e);
        }
        return false;
    }

    public ResultSet executeQuery() throws SQLException {
        try {
            this.cursor = this.connection.getDatabase().rawQuery(getSql(), bindingsToArray());
            CursorResultSet cursorResultSet = new CursorResultSet(this, this.cursor, false);
            this.queryResult = cursorResultSet;
            return cursorResultSet;
        } catch (SQLiteException e) {
            SqlitexConnection.throwSQLException(e);
            return null;
        }
    }

    public int executeUpdate() throws SQLException {
        if (this.autoGeneratedKeys == 1) {
            try {
                this.insertResult = new SingleResultSet(this, this.statement.executeInsert());
                this.updateCount = 1;
            } catch (SQLiteException e) {
                SqlitexConnection.throwSQLException(e);
            }
        } else {
            try {
                this.updateCount = this.statement.executeUpdateDelete();
            } catch (SQLiteException e2) {
                SqlitexConnection.throwSQLException(e2);
            }
        }
        return this.updateCount;
    }
}
