package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import com.facebook.appevents.AppEventsConstants;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.upstream.DefaultLoadErrorHandlingPolicy;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@zzark
public final class zzaan {
    private static final zzaac<String> zzcnv = zzaac.zzb(0, "gads:sdk_core_experiment_id");
    public static final zzaac<String> zzcnw = zzaac.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static final zzaac<String> zzcnx = zzaac.zza(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final zzaac<Boolean> zzcny = zzaac.zza(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static final zzaac<String> zzcnz = zzaac.zzb(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final zzaac<String> zzcoa = zzaac.zzb(0, "gads:request_builder:refresh_if_destroyed:experiment_id");
    public static final zzaac<Boolean> zzcob = zzaac.zza(0, "gads:request_builder:refresh_if_destroyed:enable", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcoc = zzaac.zza(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static final zzaac<String> zzcod = zzaac.zzb(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzaac<Boolean> zzcoe = zzaac.zza(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcof = zzaac.zza(0, "gads:report_dynamite_crash_in_background_thread", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcog = zzaac.zza(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final zzaac<String> zzcoh = zzaac.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzaac<Float> zzcoi = zzaac.zza(1, "gads:trapped_exception_sample_rate", 0.01f);
    private static final zzaac<String> zzcoj = zzaac.zzb(0, "gads:block_autoclicks_experiment_id");
    private static final zzaac<String> zzcok = zzaac.zzb(0, "gads:spam_app_context:experiment_id");
    private static final zzaac<Integer> zzcol = zzaac.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzaac<String> zzcom = zzaac.zza(1, "gads:video_exo_player:version", AppEventsConstants.EVENT_PARAM_VALUE_YES);
    public static final zzaac<Integer> zzcon = zzaac.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzaac<Integer> zzcoo = zzaac.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzaac<Integer> zzcop = zzaac.zza(1, "gads:video_exo_player:loading_check_interval", (int) ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES);
    public static final zzaac<Integer> zzcoq = zzaac.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzaac<Integer> zzcor = zzaac.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    private static final zzaac<String> zzcos = zzaac.zzb(0, "gads:video_stream_cache:experiment_id");
    public static final zzaac<Integer> zzcot = zzaac.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzaac<Integer> zzcou = zzaac.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzaac<Integer> zzcov = zzaac.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzaac<Long> zzcow = zzaac.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzaac<Long> zzcox = zzaac.zza(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzaac<Integer> zzcoy = zzaac.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzaac<Boolean> zzcoz = zzaac.zza(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final zzaac<String> zzcpa = zzaac.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzaac<Long> zzcpb = zzaac.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzaac<Boolean> zzcpc = zzaac.zza(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final zzaac<Long> zzcpd = zzaac.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzaac<Boolean> zzcpe = zzaac.zza(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final zzaac<Integer> zzcpf = zzaac.zza(1, "gads:video:spinner:scale", 4);
    public static final zzaac<Long> zzcpg = zzaac.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzaac<Boolean> zzcph = zzaac.zza(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcpi = zzaac.zza(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final zzaac<String> zzcpj = zzaac.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzaac<Integer> zzcpk = zzaac.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static final zzaac<Float> zzcpl = zzaac.zza(0, "gads:ad_id_app_context:ping_ratio", (float) BitmapDescriptorFactory.HUE_RED);
    private static final zzaac<String> zzcpm = zzaac.zzb(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final zzaac<Boolean> zzcpn = zzaac.zza(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    private static final zzaac<Float> zzcpo = zzaac.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", (float) BitmapDescriptorFactory.HUE_RED);
    private static final zzaac<Boolean> zzcpp = zzaac.zza(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcpq = zzaac.zza(0, "gads:ad_id:use_ipc:enabled", Boolean.valueOf(false));
    public static final zzaac<String> zzcpr = zzaac.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzaac<String> zzcps = zzaac.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzaac<String> zzcpt = zzaac.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzaac<String> zzcpu = zzaac.zza(1, "gad:mraid:version", "2.0");
    public static final zzaac<Boolean> zzcpv = zzaac.zza(1, "gads:mraid:unload", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcpw = zzaac.zza(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final zzaac<String> zzcpx = zzaac.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzaac<Boolean> zzcpy = zzaac.zza(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcpz = zzaac.zza(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final zzaac<Integer> zzcqa = zzaac.zza(0, "gads:content_length_weight", 1);
    public static final zzaac<Integer> zzcqb = zzaac.zza(0, "gads:content_age_weight", 1);
    public static final zzaac<Integer> zzcqc = zzaac.zza(0, "gads:min_content_len", 11);
    public static final zzaac<Integer> zzcqd = zzaac.zza(0, "gads:fingerprint_number", 10);
    public static final zzaac<Integer> zzcqe = zzaac.zza(0, "gads:sleep_sec", 10);
    public static final zzaac<Integer> zzcqf = zzaac.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzaac<Integer> zzcqg = zzaac.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzaac<Integer> zzcqh = zzaac.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzaac<String> zzcqi = zzaac.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzaac<String> zzcqj = zzaac.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzaac<Boolean> zzcqk = zzaac.zza(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcql = zzaac.zza(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final zzaac<Long> zzcqm = zzaac.zza(0, "gads:app_index:timeout_ms", 1000);
    private static final zzaac<String> zzcqn = zzaac.zzb(0, "gads:app_index:experiment_id");
    public static final zzaac<Boolean> zzcqo = zzaac.zza(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcqp = zzaac.zza(1, "gads:sai:enabled", Boolean.valueOf(true));
    public static final zzaac<String> zzcqq = zzaac.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzaac<String> zzcqr = zzaac.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzaac<Boolean> zzcqs = zzaac.zza(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    public static final zzaac<String> zzcqt = zzaac.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzaac<Long> zzcqu = zzaac.zza(1, "gads:sai:timeout_ms", -1);
    public static final zzaac<Integer> zzcqv = zzaac.zza(1, "gads:sai:scion_thread_pool_size", 5);
    private static final zzaac<Boolean> zzcqw = zzaac.zza(1, "gads:sai:app_measurement_enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcqx = zzaac.zza(1, "gads:sai:force_through_reflection", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcqy = zzaac.zza(1, "gads:sai:gmscore_availability_check_disabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcqz = zzaac.zza(1, "gads:sai:logging_disabled_for_drx", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcra = zzaac.zza(1, "gads:interstitial:app_must_be_foreground:enabled", Boolean.valueOf(false));
    private static final zzaac<Integer> zzcrb = zzaac.zza(0, "gads:webview_cache_version", 0);
    public static final zzaac<Boolean> zzcrc = zzaac.zza(0, "gads:corewebview:adwebview_factory:enable", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcrd = zzaac.zza(0, "gads:corewebview:javascript_engine", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcre = zzaac.zza(1, "gad:webview:inject_scripts", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcrf = zzaac.zza(0, "gads:webview:permission:disabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcrg = zzaac.zzc(0, "gads:pan:experiment_id");
    private static final zzaac<Boolean> zzcrh = zzaac.zza(1, "gads:new_rewarded_ad:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcri = zzaac.zza(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final zzaac<Long> zzcrj = zzaac.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzaac<Boolean> zzcrk = zzaac.zza(1, "gads:rewarded:ad_metadata_enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcrl = zzaac.zza(1, "gads:rewarded:ssv_custom_data_enabled", Boolean.valueOf(true));
    public static final zzaac<Long> zzcrm = zzaac.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzaac<Long> zzcrn = zzaac.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzaac<Boolean> zzcro = zzaac.zza(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final zzaac<Long> zzcrp = zzaac.zza(1, "gads:adid_values_in_adrequest:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzaac<Boolean> zzcrq = zzaac.zza(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcrr = zzaac.zza(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    public static final zzaac<Long> zzcrs = zzaac.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzaac<Boolean> zzcrt = zzaac.zza(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcru = zzaac.zza(1, "gads:disabling_closable_area:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcrv = zzaac.zza(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcrw = zzaac.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzaac<Integer> zzcrx = zzaac.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzaac<Integer> zzcry = zzaac.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzaac<Boolean> zzcrz = zzaac.zza(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcsa = zzaac.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final zzaac<String> zzcsb = zzaac.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzaac<String> zzcsc = zzaac.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzaac<Integer> zzcsd = zzaac.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzaac<Integer> zzcse = zzaac.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzaac<Integer> zzcsf = zzaac.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzaac<String> zzcsg = zzaac.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzaac<Integer> zzcsh = zzaac.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzaac<Integer> zzcsi = zzaac.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzaac<Long> zzcsj = zzaac.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final zzaac<Long> zzcsk = zzaac.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final zzaac<Float> zzcsl = zzaac.zza(1, "gads:interstitial_ad_pool:discard_asymptote", (float) BitmapDescriptorFactory.HUE_RED);
    public static final zzaac<Float> zzcsm = zzaac.zza(1, "gads:interstitial_ad_pool:miss_asymptote", (float) BitmapDescriptorFactory.HUE_RED);
    public static final zzaac<Boolean> zzcsn = zzaac.zza(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcso = zzaac.zza(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    private static final zzaac<Integer> zzcsp = zzaac.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzaac<String> zzcsq = zzaac.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzaac<String> zzcsr = zzaac.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzaac<Boolean> zzcss = zzaac.zza(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcst = zzaac.zza(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final zzaac<Long> zzcsu = zzaac.zza(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzaac<Long> zzcsv = zzaac.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final zzaac<Boolean> zzcsw = zzaac.zza(1, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcsx = zzaac.zza(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcsy = zzaac.zza(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcsz = zzaac.zza(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcta = zzaac.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    private static final zzaac<Long> zzctb = zzaac.zza(1, "gads:rtb_signal_timeout_ms", 1000);
    private static final zzaac<Boolean> zzctc = zzaac.zza(1, "gads:rtb_cld:enabled", Boolean.valueOf(false));
    public static final zzaac<Long> zzctd = zzaac.zza(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final zzaac<Long> zzcte = zzaac.zza(0, "gads:ad_loader:timeout_ms", (long) DefaultLoadErrorHandlingPolicy.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzaac<Long> zzctf = zzaac.zza(0, "gads:rendering:timeout_ms", (long) DefaultLoadErrorHandlingPolicy.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzaac<Boolean> zzctg = zzaac.zza(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final zzaac<Long> zzcth = zzaac.zza(1, "gads:gestures:task_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzaac<Boolean> zzcti = zzaac.zza(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzctj = zzaac.zza(1, "gads:gestures:ans:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzctk = zzaac.zza(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzctl = zzaac.zza(1, "gads:gestures:brt:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzctm = zzaac.zza(1, "gads:signal:app_permissions:disabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzctn = zzaac.zza(1, "gads:gestures:inthex:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcto = zzaac.zza(1, "gads:gestures:hpk:enabled", Boolean.valueOf(true));
    public static final zzaac<String> zzctp = zzaac.zza(1, "gads:gestures:pk", "");
    public static final zzaac<Boolean> zzctq = zzaac.zza(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzctr = zzaac.zza(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcts = zzaac.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzctt = zzaac.zza(0, "gass:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzctu = zzaac.zza(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzctv = zzaac.zza(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    private static final zzaac<Boolean> zzctw = zzaac.zza(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static final zzaac<String> zzctx = zzaac.zzb(1, "gads:sdk_core_constants:experiment_id");
    public static final zzaac<String> zzcty = zzaac.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzaac<Long> zzctz = zzaac.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzaac<Boolean> zzcua = zzaac.zza(0, "gads:js_flags:mf", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcub = zzaac.zza(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcuc = zzaac.zza(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final zzaac<String> zzcud = zzaac.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzaac<String> zzcue = zzaac.zza(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final zzaac<String> zzcuf = zzaac.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzaac<String> zzcug = zzaac.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzaac<Integer> zzcuh = zzaac.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzaac<Integer> zzcui = zzaac.zza(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final zzaac<String> zzcuj = zzaac.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzaac<Boolean> zzcuk = zzaac.zza(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcul = zzaac.zza(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcum = zzaac.zza(1, "gads:native:media_view_match_parent:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcun = zzaac.zza(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcuo = zzaac.zza(1, "gads:native:custom_one_point_five_click:enable", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcup = zzaac.zza(1, "gads:unified_native_ad:enable", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcuq = zzaac.zza(1, "gads:instream_ad:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcur = zzaac.zza(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcus = zzaac.zza(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    private static final zzaac<String> zzcut = zzaac.zzc(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzaac<Long> zzcuu = zzaac.zza(1, "gads:auto_location_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzaac<String> zzcuv = zzaac.zzc(1, "gads:auto_location_timeout:experiment_id");
    private static final zzaac<Long> zzcuw = zzaac.zza(1, "gads:auto_location_interval", -1);
    private static final zzaac<String> zzcux = zzaac.zzc(1, "gads:auto_location_interval:experiment_id");
    private static final zzaac<Boolean> zzcuy = zzaac.zza(0, "gads:auto_location_interval:without_thread", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcuz = zzaac.zza(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcva = zzaac.zzb(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzaac<Long> zzcvb = zzaac.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static final zzaac<String> zzcvc = zzaac.zzb(0, "gads:afs:csa:experiment_id");
    public static final zzaac<String> zzcvd = zzaac.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzaac<String> zzcve = zzaac.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzaac<String> zzcvf = zzaac.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzaac<String> zzcvg = zzaac.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzaac<String> zzcvh = zzaac.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzaac<Long> zzcvi = zzaac.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final zzaac<Long> zzcvj = zzaac.zza(1, "gads:parental_controls:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzaac<String> zzcvk = zzaac.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final zzaac<Long> zzcvl = zzaac.zza(0, "gads:safe_browsing:safety_net:delay_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzaac<Boolean> zzcvm = zzaac.zza(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    private static final zzaac<Integer> zzcvn = zzaac.zza(1, "gads:cache:ad_request_timeout_millis", (int) Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static final zzaac<Integer> zzcvo = zzaac.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzaac<Long> zzcvp = zzaac.zza(1, "gads:cache:javascript_timeout_millis", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzaac<Boolean> zzcvq = zzaac.zza(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcvr = zzaac.zza(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcvs = zzaac.zza(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final zzaac<Long> zzcvt = zzaac.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzaac<Boolean> zzcvu = zzaac.zza(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcvv = zzaac.zza(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    public static final zzaac<Long> zzcvw = zzaac.zza(1, "gads:cache:connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzaac<Long> zzcvx = zzaac.zza(1, "gads:cache:read_only_connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzaac<Boolean> zzcvy = zzaac.zza(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    public static final zzaac<String> zzcvz = zzaac.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzaac<Integer> zzcwa = zzaac.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzaac<Boolean> zzcwb = zzaac.zza(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwc = zzaac.zza(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwd = zzaac.zza(1, "gads:debug_hold_gesture:enabled", Boolean.valueOf(false));
    public static final zzaac<Long> zzcwe = zzaac.zza(1, "gads:debug_hold_gesture:time_millis", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzaac<String> zzcwf = zzaac.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzaac<String> zzcwg = zzaac.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzaac<String> zzcwh = zzaac.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzaac<String> zzcwi = zzaac.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzaac<Integer> zzcwj = zzaac.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzaac<Integer> zzcwk = zzaac.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzaac<Boolean> zzcwl = zzaac.zza(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwm = zzaac.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwn = zzaac.zza(1, "gad:interstitial_multi_window_method", Boolean.valueOf(false));
    public static final zzaac<Integer> zzcwo = zzaac.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzaac<Boolean> zzcwp = zzaac.zza(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwq = zzaac.zza(1, "gads:clearcut_logging:write_to_file", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcwr = zzaac.zza(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcws = zzaac.zza(1, "gad:publisher_testing:force_local_request:enabled", Boolean.valueOf(false));
    public static final zzaac<String> zzcwt = zzaac.zza(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    public static final zzaac<String> zzcwu = zzaac.zza(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    public static final zzaac<Boolean> zzcwv = zzaac.zza(0, "gad:force_dynamite_loading_enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcww = zzaac.zzb(0, "gad:dynamite_module:experiment_id");
    public static final zzaac<Integer> zzcwx = zzaac.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzaac<Boolean> zzcwy = zzaac.zza(1, "gads:omid:enabled", Boolean.valueOf(false));
    public static final zzaac<Integer> zzcwz = zzaac.zza(1, "gads:omid:destroy_webview_delay", 1000);
    private static final zzaac<Boolean> zzcxa = zzaac.zza(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxb = zzaac.zza(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcxc = zzaac.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final zzaac<Boolean> zzcxd = zzaac.zza(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcxe = zzaac.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final zzaac<Boolean> zzcxf = zzaac.zza(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxg = zzaac.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcxh = zzaac.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final zzaac<Boolean> zzcxi = zzaac.zza(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    private static final zzaac<String> zzcxj = zzaac.zza(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final zzaac<Boolean> zzcxk = zzaac.zza(1, "gads:nonagon:banner:check_dp_size", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxl = zzaac.zza(1, "gads:nonagon:rewarded:load_multiple_ads", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcxm = zzaac.zza(1, "gads:nonagon:return_last_error_code", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxn = zzaac.zza(1, "gads:nonagon:return_no_fill_error_code", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxo = zzaac.zza(1, "gads:nonagon:continue_on_no_fill", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcxp = zzaac.zza(1, "gads:nonagon:open_not_loaded_interstitial", Boolean.valueOf(true));
    private static final zzaac<Boolean> zzcxq = zzaac.zza(1, "gads:nonagon:separate_timeout:enabled", Boolean.valueOf(false));
    private static final zzaac<Integer> zzcxr = zzaac.zza(1, "gads:nonagon:request_timeout:seconds", 60);
    private static final zzaac<Boolean> zzcxs = zzaac.zza(0, "gads:nonagon:limit_ad_request_connection", Boolean.valueOf(true));
    private static final zzaac<Boolean> zzcxt = zzaac.zza(1, "gads:nonagon:javascript_ad_request:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxu = zzaac.zza(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxv = zzaac.zza(1, "gads:signals:ad_id_info:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxw = zzaac.zza(1, "gads:signals:app_index:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxx = zzaac.zza(1, "gads:signals:cache:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcxy = zzaac.zza(1, "gads:signals:doritos:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcxz = zzaac.zza(1, "gads:signals:doritos:v1:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcya = zzaac.zza(1, "gads:signals:location:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcyb = zzaac.zza(1, "gads:signals:network_prediction:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcyc = zzaac.zza(1, "gads:signals:parental_control:enabled", Boolean.valueOf(false));
    private static final zzaac<Boolean> zzcyd = zzaac.zza(1, "gads:signals:video_decoder:enabled", Boolean.valueOf(false));
    public static final zzaac<Long> zzcye = zzaac.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzaac<String> zzcyf = zzaac.zza(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final zzaac<Integer> zzcyg = zzaac.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzaac<Integer> zzcyh = zzaac.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final zzaac<Integer> zzcyi = zzaac.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final zzaac<Integer> zzcyj = zzaac.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final zzaac<Boolean> zzcyk = zzaac.zza(0, "gads:rewarded_sku:enabled", Boolean.valueOf(true));
    private static final zzaac<Boolean> zzcyl = zzaac.zza(0, "gads:rewarded_sku:override_test:enabled", Boolean.valueOf(false));
    public static final zzaac<Boolean> zzcym = zzaac.zza(1, "gads:consent:shared_preference_reading:enabled", Boolean.valueOf(true));
    public static final zzaac<Boolean> zzcyn = zzaac.zza(1, "gads:consent:iab_consent_info:enabled", Boolean.valueOf(true));
    private static final zzaac<Boolean> zzcyo = zzaac.zza(1, "gads:nativeads:image:sample:enabled", Boolean.valueOf(true));
    private static final zzaac<Integer> zzcyp = zzaac.zza(1, "gads:nativeads:image:sample:pixels", (int) ExtractorMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES);
    public static final zzaac<Integer> zzcyq = zzaac.zza(0, "gads:dynamite_load:fail:sample_rate", 10000);
    private static final zzaac<Boolean> zzcyr = zzaac.zza(0, "gads:service:webview:enable_directory_suffix", Boolean.valueOf(true));
    private static byte[] zzcys;

    public static void initialize(Context context) {
        zzbak.zza(context, new zzaao(context));
        int intValue = ((Integer) zzwu.zzpz().zzd(zzcsp)).intValue();
        if (intValue > 0 && zzcys == null) {
            zzcys = new byte[intValue];
        }
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzwu.zzpx();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzwu.zzpy().zza(edit, 1, jSONObject);
        zzwu.zzpx();
        edit.commit();
    }

    public static List<String> zzqw() {
        return zzwu.zzpy().zzqw();
    }

    public static List<String> zzqx() {
        return zzwu.zzpy().zzqx();
    }
}
